### ISSUE TITLE
Smapi stardew crashes 

### ISSUE THREAD

**Issue by DARKASHER** [ZaneYork/SMAPI-Android-Installer#10]
I noticed that smapi stardew crashed a lot after the last update (1,4.6) without saving.

**Comment by ZaneYork** [comment]
Could you please provide the error logs? I can locate the issue without the error log

**Comment by DARKASHER** [comment]
https://smapi.io/log/014efccd0436422e961609692529b82b
Idk if it crashes because i use many mods but before the last update it was working fine .po

**Comment by ZaneYork** [comment]
> https://smapi.io/log/014efccd0436422e961609692529b82b
> Idk if it crashes because i use many mods but before the last update it was working fine .po

There is no error in the log, do you have any screenshot of the issue to describe this?

**Comment by DARKASHER** [comment]
No it's just force stop and get out from the app suddenly without saving and that's so annoying

**Comment by ZaneYork** [comment]
> No it's just force stop and get out from the app suddenly without saving and that's so annoying

Please provide the error log when your game is crashed ( do not enter the game again before you upload the crash log)

**Comment by ZaneYork** [comment]
> No it's just force stop and get out from the app suddenly without saving and that's so annoying

Fixed some save logic in latest 1.4.7 release, you can check if it is fixed or not

**Comment by DARKASHER** [comment]
I think it works fine now, will you fix the problem when i quit smapi stardew without closing it and back into it it restart? Sometimes i need to go to an assistant when i back to the game it restart, and all the progress of the day went off .

**Comment by ZaneYork** [comment]
> I think it works fine now, will you fix the problem when i quit smapi stardew without closing it and back into it it restart? Sometimes i need to go to an assistant when i back to the game it restart, and all the progress of the day went off .

I also fixed an issue of this(not confirmed), you can test it

**Comment by DARKASHER** [comment]
Sadlyit still exists

**Comment by DARKASHER** [comment]
It just crashed again Twice in a row

**Comment by DARKASHER** [comment]
https://smapi.io/log/c2c9e40dda664289bcc54cd574ef9a3f

**Comment by DARKASHER** [comment]
Wow ! I didn't face any crashes since the last update... Thank you for the great work !
