### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by jordannoie** [ZaneYork/SMAPI-Android-Installer#121]
Is anyone having luck with a game version that is working? I used 1.4.5.145 and experienced the no music problem. Tried 1.4.8 and 1.5.1 and the game froze. Not sure what to do? Any links?

**Comment by haruki83** [comment]
Try 1.4.5.151 or maybe wait till 1.5

**Comment by lividhen** [comment]
What device do you have?

**Comment by ZaneYork** [comment]
Duplicate of #54
