### ISSUE TITLE
SMAPI KEEP ON CRASHING WITHOUT ERROR LOG

### ISSUE THREAD

**Issue by aselolejosss** [ZaneYork/SMAPI-Android-Installer#125]
![Screenshot_2021-03-15-22-40-02-157_com miui home](https://user-images.githubusercontent.com/80700983/111184347-7875f980-85e3-11eb-8f6a-6a4b1315bf33.jpg)

Smapi stardew valley keep on crashing eveytime I open it for the first time.
I use Xiaomi redmi note 8 pro
Smapi version 3.7.6.8
Stardew Valley version 1.4.5.148
I've been trying everything for hours
No error log, please help I'm frustrating.

**Comment by aselolejosss** [comment]
@ZaneYork please help

**Comment by Rosmar22** [comment]
Same issue with me..

**Comment by ZaneYork** [comment]
Duplicate of #175

**Comment by Reficco** [comment]
To open your smapi, Get The Latest Old Version Of your game

Info : Stardew valley 1.4.5.142 is work to SMAPI Open 100% ☺☺☺☺
