### ISSUE TITLE
can't play SVE on 3.7.6.9 SMAPI on android

### ISSUE THREAD

**Issue by atriajii** [ZaneYork/SMAPI-Android-Installer#127]
the game just kept crashing even before i open the game, i deleted my other mods too. i saw the log but i can't understand it since i'm just new to modding and i'm not familiar with codes. can someone help me step by step? heres the log: https://smapi.io/log/a19d31d45aa748e1ae4f12d2f8f1c3af

**Comment by firereverie** [comment]
Tried updating pytk? Most of your errors seem to revolve around it, try 1.19.6 I believe that’s the current supported version in the patch notes, and the most recent update pre-SDV 1.5 on the nexus.

**Comment by GuardianMilky** [comment]
I dunno what should I do here but... I downloaded all the files pre-1.5 of SDV for PC(I assumed they are at thr 1.4 version but I guess I was wrong). The game run 1 time till I went down the bus, until all the cutscenes are gone and the game crashed. Any idea as to why that happened? Here's the log btw.

https://smapi.io/log/a1ccbd5d0314402d960060f9ef8e8439

**Comment by GuardianMilky** [comment]
Maybe we can move down even further on the download files and hope that one of those will work. Anyway, I hope can someone find a solution for this cause I am currently playing SVE with IFR2 Remastered on my pc and I find it fun actually so I wanted to play it too on my mobile.

**Comment by GuardianMilky** [comment]
I find a thread saying that SVE 1.11 works so you might want to give that a try. Who knows if it'll run or not?

**Comment by ZaneYork** [comment]
Duplicate of #141
