### ISSUE TITLE
Can't install Smapi Stardew Valley

### ISSUE THREAD

**Issue by MrXarl** [ZaneYork/SMAPI-Android-Installer#128]
Hello, I've been trying to fix this error for half a year, but nothing. No, I can install Smapi, but Smapi cannot install Smapi Stardew Valley. I am using version 1.4.5.148

**Comment by ialil** [comment]
Same problem mine said failed to sign the game please contact the developer for help

**Comment by Melo426** [comment]
same here

**Comment by Melo426** [comment]
someone discovered how to fix this?

**Comment by ZaneYork** [comment]
Duplicate of #178
