### ISSUE TITLE
Smapı crash

### ISSUE THREAD

**Issue by DemiurgeSan** [ZaneYork/SMAPI-Android-Installer#13]
Can anyone help. Android version smapı. Crash after open
![Screenshot_2020-05-24-13-27-53-727_com miui bugreport](https://user-images.githubusercontent.com/65851738/82758153-8c026a80-9ded-11ea-9c67-f5d31a75c26c.jpg)
![Screenshot_2020-05-24-13-28-00-431_com miui bugreport](https://user-images.githubusercontent.com/65851738/82758155-8d339780-9ded-11ea-8ec7-8a010398b35e.jpg)

**Comment by ZaneYork** [comment]
Test latest 1.5.2 version, it may fix or detect this issue.Make sure  you had installed the official version of the Stardew Valley

**Comment by ZaneYork** [comment]
Duplicate of #175
