### ISSUE TITLE
SMAPI Android Update 3.9.0

### ISSUE THREAD

**Issue by Gener0185** [ZaneYork/SMAPI-Android-Installer#141]
I was` wondering when are you gonna update smapi to 3.9.0 ???because content patcher is not working without that version

**Comment by lividhen** [comment]
I think 3.9.0 is for a newer version of stardew valley than the mobile version has been updated, so an update to it would be impossible. Use the version that says its for android on it's nexusmods page.
https://www.nexusmods.com/stardewvalley/mods/1915?tab=files

**Comment by Rijan2** [comment]
Can u like plz update smapi android to 3.9.5 cause I wanna run mods but they r getting updated to smapi 3.9.5 and it's not out yet?

**Comment by lividhen** [comment]
> 
> 
> Can u like plz update smapi android to 3.9.5 cause I wanna run mods but they r getting updated to smapi 3.9.5 and it's not out yet?

Smapi 3.9.5 is for a newer version of Stardew Valley than is released on mobile. It would not be possible to port it until the mobile version of Stardew gets an update. If you are using nexusmods, you can scroll down in the files tab of the mod, and under the "OLD FILES" section, download a version that is compatible with Smapi 3.7.

**Comment by GuardianMilky** [comment]
> Can u like plz update smapi android to 3.9.5 cause I wanna run mods but they r getting updated to smapi 3.9.5 and it's not out yet?

Not possible until Stardew Valley Mobile updates to 1.5. What you can do tho is look for older files that are pre-1.5 and hope that it works.

**Comment by ZaneYork** [comment]
The SMAPI for Android cannot be updated unless the game version for mobile platform upgrade to 1.5

**Comment by Zahshane** [comment]
Stardew valley smapi don't work

**Comment by Zahshane** [comment]
> The SMAPI for Android cannot be updated unless the game version for mobile platform upgrade to 1.5

You mean Smapi don't work with indroid?
Sorry for bad English

**Comment by ZaneYork** [comment]
Will update to latest version
