### ISSUE TITLE
Music Not Working

### ISSUE THREAD

**Issue by LotusRiver** [ZaneYork/SMAPI-Android-Installer#146]
Music still isn't working. Im on Galaxy Note 20 Ultra. Works fine outside of SMAPI, I have 0 mods installed and it still doesn't work with this version of SMAPI. I love the music so it's mildly disappointing. No hate to the dev, you're doing a great job!

**Comment by lividhen** [comment]
Duplicate of [#54](https://github.com/ZaneYork/SMAPI-Android-Installer/issues/54#issuecomment-864800295)

**Comment by ZaneYork** [comment]
Duplicate of #54
