### ISSUE TITLE
Ui bug in ChestsanyWhere

### ISSUE THREAD

**Issue by ErikK194** [ZaneYork/SMAPI-Android-Installer#150]
![Screenshot_20210915-213006_b455cd2e68c7bcd1c56b48948a696206](https://user-images.githubusercontent.com/21066327/133499549-b7af0fe0-f199-498e-926e-f0c80525d045.jpg)
everything else works, except the edit button (not displayed)

In use:
SMAPI 3.7.6.1
ChestsAnywhere 1.19.8

**Comment by ZaneYork** [comment]
This is a issue of mod itself
