### ISSUE TITLE
Failed To Sign The App, Pleas ask developer for help

### ISSUE THREAD

**Issue by Selman5336** [ZaneYork/SMAPI-Android-Installer#163]
When I try to install smapi I get this Error text. 
![Screenshot_20220113-172355_SMAPI Installer](https://user-images.githubusercontent.com/97689911/149368835-e31318e9-7b00-4c42-ba79-dc5fda2c36b8.jpg)
How can I fix this??

**Comment by ImPudding-tech** [comment]
Heyy.. If Haven't Found The Solution Yet.. I Have A Solution....

Install The Smapi 3.7.6.3

Because It Works For me....
https://github.com/ZaneYork/SMAPI-Android-Installer/releases/tag/v3.7.6.3

**Comment by Andremamanks** [comment]
What Stardew version you're using?

**Comment by lividhen** [comment]
Are you using Stardew Valley 1.4.5.151?

**Comment by Selman5336** [comment]
Yes I was, I downgraded my game then smapi worked. Thx

lividhen ***@***.***> schrieb am Mi., 9. Feb. 2022, 21:52:

**Comment by ZaneYork** [comment]
Duplicate of #178
