### ISSUE TITLE
Bisa kah membantu saya memasang mod zuzu city

### ISSUE THREAD

**Issue by Ahmadsafri01** [ZaneYork/SMAPI-Android-Installer#168]
![Screenshot_20220130-105311](https://user-images.githubusercontent.com/57864097/151685565-e96bc0b1-2108-47e0-ab68-73289d22a158.jpg)

I don't understand where I went wrong, I've mutually changed the file but still the problem hasn't changed and is gone. I'm desperate maybe some of you can help, I appreciate it that. so please comment so I can install this zuzu city mod on my phone

**Comment by Ahmadsafri01** [comment]
Please help me

**Comment by lividhen** [comment]
You will need to use older versions of the mods that are meant for SMAPI 3.7 if they exist.

**Comment by ZaneYork** [comment]
Duplicate of #141
