### ISSUE TITLE
This problem is actually need to be fix

### ISSUE THREAD

**Issue by Andremamanks** [ZaneYork/SMAPI-Android-Installer#169]
![Screenshot_2022-02-03-12-46-02-995_com zane smapiinstaller](https://user-images.githubusercontent.com/61966036/152288186-7bc4ee8e-deb4-4404-b158-e70bfcedcb89.jpg)

like why? on the old time it can be used but now.. why it doesn't work again? and how do I fix this? uninstall the modded base apps? I used mod that probably the issue but I'm still confused

**Comment by Andremamanks** [comment]
Duplicate of #163 Btw

**Comment by Andremamanks** [comment]
oh wait... nvm it's just need the older version of smapi in order to patch the version of 1.4.5.151... I guess I need to closes this now

**Comment by Andremamanks** [comment]
how to fix this issues if you use 1.4.5.151 Stardew valley
just downgrade the SMAPI to the pre-release version of it and find the latest version of the pre-release smapi and it will work.. I already tried it

**Comment by Mighty-Mozart** [comment]
Can you please give me the link for downgrade my SMAPI, I can't find it
