### ISSUE TITLE
how to activate the music?

### ISSUE THREAD

**Issue by Edw13Edu13** [ZaneYork/SMAPI-Android-Installer#188]
Every time I access smapi SV it asks for permission to access obb but it doesn't change anything, it's not working!

**Comment by ZaneYork** [comment]
Please leave your OS vendor info and device info

**Comment by Edw13Edu13** [comment]
the music just came back, I just restarted it and it worked perfectly, a thousand apologies for the inconvenience

**Comment by ZaneYork** [comment]
Duplicate of #54
