### ISSUE TITLE
Button overlap

### ISSUE THREAD

**Issue by ellipszist** [ZaneYork/SMAPI-Android-Installer#21]
![Screenshot_20200622-181941_SMAPI_Installer](https://user-images.githubusercontent.com/43781364/85386014-3b596b00-b56d-11ea-963c-598d9b5cec8b.jpg)
Install button overlap on text in the middle of screen.

**Comment by ZaneYork** [comment]
[Fixed](https://github.com/ZaneYork/SMAPI-Android-Installer/commit/c1e78870042019feaeaebb6cf900715d3454459b)
