### ISSUE TITLE
Cannot load the save file(probably due to custom localization)

### ISSUE THREAD

**Issue by lianmola** [ZaneYork/SMAPI-Android-Installer#22]
The game gets stuck on the loading screen and never opens every time I try to open my save. I think it isn't a save file problem because it's always like that with the new games too. Removing all the mods fixes the problem, but it happens all over again if there is a single mod in the mods folder. I don't know whether it's a mod error or a smapi error but I could really use some help. My error logs are here below:

https://smapi.io/log/e94a218bcfcf4663ac7948768adc124c

**Comment by PrimAstrid** [comment]
I have the same problem. It freezes on the "loading part...". I close the app and restart the game but the same thing happens.

**Comment by PrimAstrid** [comment]
i tried to find the SMAPI Installer in Google Play but it says "Item not found". Does anyone have any other link where to dl the 3.5 or better, 3.6 version?

**Comment by lianmola** [comment]
https://github.com/ZaneYork/SMAPI-Android-Installer/releases
Past android smapi releases are right here in github. And I think I singled out the mod responsible - I think it's the problem with Custom Localization at the moment. Which I didn't have a clue because the smapi couldn't detect this...

**Comment by PrimAstrid** [comment]
Any luck? 💔

**Comment by lianmola** [comment]
I am pretty sure it's the custom localization problem now, but I don't have a clue how to deal with this so I am playing the game without that mod😂

**Comment by PrimAstrid** [comment]
I was able to load it. So ummm.. not really sure what happened but as far as I remember, I deleted the Custom Localization in my Mods folder. Then, I downloaded the SDV_Custom Localization 1.1.0.zip on this version and transferred it to my Mods folder. When I opened the game, it says that the Custom Localization doesn't work bec it was missing the Custom Localization.dll file (bec i deleted beforehand). Thats it. 1 out of 2 load games was able to start. Hope it works for you too. :)

**Comment by lianmola** [comment]
I loaded it! I'm completely oblivious of how this happened but when I reinstalled the smapi Custom localization started to work. But when the smapi first crashed I was playing SVE too so I think it might have something to do with the SVE mod.
