### ISSUE TITLE
Failed to initialize

### ISSUE THREAD

**Issue by YeiserDeveloper** [ZaneYork/SMAPI-Android-Installer#229]
![Screenshot_2022-08-11-09-53-08-013_com.zane.stardewvalley.jpg](https://user-images.githubusercontent.com/97372908/184150653-e8e76fd7-6f93-45d0-ba4d-5ec43b61738b.jpg)

**Comment by Physicalxi** [comment]
Same issue. Also ZaneYork marked this same issue as a bug https://github.com/ZaneYork/SMAPI-Android-Installer/issues/189
