### ISSUE TITLE
not working in version 1.4.5.145

### ISSUE THREAD

**Issue by TheDarkness2004** [ZaneYork/SMAPI-Android-Installer#23]
I installed and uninstalled it several times and it always keeps the screen black and doesn't work. I'm on the latest version of Stardew Valley and Smapi and on Android 10, I don't know if it's because of my Android

**Comment by 1jezs0** [comment]
I think this version of smapi doesnt support android 10

**Comment by ZaneYork** [comment]
Needs more details for the issue such as error logs or logcat report to locate the problem

**Comment by ZaneYork** [comment]
Duplicate of #175
