### ISSUE TITLE
SMAPI needs updating

### ISSUE THREAD

**Issue by ThisIsAyato** [ZaneYork/SMAPI-Android-Installer#248]
Eric updated stardew valley mobile to 1.5 today but I can't play this version because my save is from stardew valley expanded.  I wanted to know when you will be able to update smapi to the latest version

**Comment by seiralean** [comment]
Can u be patient?

**Comment by seiralean** [comment]
> Eric updated stardew valley mobile to 1.5 today but I can't play this version because my save is from stardew valley expanded. I wanted to know when you will be able to update smapi to the latest version

Can't u be patient??

**Comment by Pathoschild** [comment]
See #246 to keep discussion in one place.

**Comment by Wonder871** [comment]
Merhaba stadew valley 1.5 gelmiş sizce tahminen nezaman smapi yenilenir ?

**Comment by Pathoschild** [comment]
@Wonder871 Merhaba! Tartışmayı tek bir yerde tutmak için lütfen #246'ya bakın.
