### ISSUE TITLE
Smapi Will it be ok in 1 month?

### ISSUE THREAD

**Issue by Wonder871** [ZaneYork/SMAPI-Android-Installer#251]
Hello Will it be compatible with smapi stardew valley in 1 month

**Comment by Wonder871** [comment]
@ZaneYork I'm really sorry but after 1 month I have a 6 month military service I'm wondering

**Comment by Asjennie** [comment]
he said that it is expected to be released in march of this year

**Comment by Wonder871** [comment]
@asjennie If the saddle comes out in March, I can't enter the game for 6 months :(

**Comment by AozoraDev** [comment]
@Wonder871 
Hey, listen.
I know you really want SMAPI Android to be updated as soon as possible, I also think the same thing.

But please keep in mind that updating Android SMAPI on SV 1.5 will really take a long time because the game has been fully rewritten so the SMAPI core needs to be rewritten again (cmiiw).

Also, stop putting pressure on Zane to quickly update SMAPI. This will stress him out and most likely make him stop updating Android SMAPI.

**Comment by AozoraDev** [comment]
Why don't you just play without SMAPI? It's more fun and challenging in my opinion.

If you really want to use mods, don't update the game to v1.5

**Comment by Wonder871** [comment]
@AozoraDev I won't lie, I coded a mod myself and I want to try it in the new version, not the old one.

**Comment by Wonder871** [comment]
I hope it works in version 1.5 my mod

**Comment by Wonder871** [comment]
@AozoraDev unfortunately you are right my friend i trust him ;)

**Comment by Wonder871** [comment]
maybe smapi will be fixed before march i am patiently waiting

**Comment by Yokutso** [comment]
@Wonder871 Then if you created a mod, with a computer i guess, it means you can test it on stardew PC right ? Stop trying to invent reasons in every posts and asking people in different languages if they know when smapi comes out. Zane is the only one who knows it and he said before March, he knows there a many people waiting for his update so don't worry, he heard you. Maybe we'll be surprised to see the update before March ! But for now, we have to wait, and spamming/creating new topic about this will not speed up the release date, on top of sending useless notifications to all people following the main topic.
