### ISSUE TITLE
sincere question

### ISSUE THREAD

**Issue by GustaBCM** [ZaneYork/SMAPI-Android-Installer#278]
Hello @ZaneYork how are you? I know you've locked the collaborators-only conversation because of a few/several comments, but I was wondering if there's any progress on that to-do list? I'm not asking out of arrogance, I really appreciate your work.

**Comment by Type21Yamashiro** [comment]
yeah bc of those impatient bastard they daily update just stop! man really want to see the progress! i quite hyoe to get smapi on M.15
