### ISSUE TITLE
Add MobileAtlas xnb to Metadata

### ISSUE THREAD

**Issue by MaythornRose** [ZaneYork/SMAPI-Android-Installer#28]
I've been trying to edit UI elements by altering `LooseSpites/MobileAtlas_manually_made.xnb`. 

Pathoschild gave me the following advice since nothing I did would work:
`The patch is loaded and ready, but the game never requested the asset. That's probably because the asset was loaded before Content Patcher, and SMAPI doesn't have asset propagation set up for that asset since it doesn't exist on PC. I suggest reporting it to the SMAPI for Android developer, and asking them to add logic for that asset to Metadata/CoreAssetPropagator.cs in the SMAPI code.`

Please and thank you!

**Comment by ZaneYork** [comment]
OK, will fix it in next release if possible

**Comment by benzaitenmu** [comment]
This should work with the update. There may be some issues with fonts that I'm still working on, and I haven't done translations yet. If you see yellow backgrounds on menu features when you start the game, then it isn't working. Everything should be in tones of white and brown.
[Vintage Interface Multipack- for ZaneYork.zip](https://github.com/ZaneYork/SMAPI-Android-Installer/files/5115194/Vintage.Interface.Multipack-.for.ZaneYork.zip)

Thank you, again! Let me know if you need any other help or want me to test. If you have Discord, I can be reached at Maythorn#1522

**Comment by ZaneYork** [comment]
Done
