### ISSUE TITLE
We want to help in the testing stage

### ISSUE THREAD

**Issue by AlexandroDRK** [ZaneYork/SMAPI-Android-Installer#289]
@ZaneYork if smapi is pretty much ready, you could update progress on the update topic to let everyone know and considerably reduce the topic of questions about the state of the smapi... As for the possible testing compile a pre-release apk to facilitate bug detection and test stability against version 1.5 mods.

**Comment by Maddigow** [comment]
Concordo plenamente

**Comment by Ze4a8** [comment]
I second that

**Comment by mymelisa** [comment]
yes please...
i'm sure a lot of us want to help in any way...we just don't know how to....

**Comment by AlexandroDRK** [comment]
Pre-release versions have started, thanks @ZaneYork for all his hard work.
