### ISSUE TITLE
Open virtual keyboart with gamepad

### ISSUE THREAD

**Issue by ZahurX** [ZaneYork/SMAPI-Android-Installer#29]
(I'm writing with google translate, sorry for the mistakes) Can you do it so that you can open the virtual keyboart and interact with it using a gamepad?

**Comment by ZaneYork** [comment]
Did you mean toggle the virtual keyboard state with hardware keys?

**Comment by ZahurX** [comment]
> Did you mean toggle the virtual keyboard state with hardware keys?

Yes P.s I think I asked a stupid question -_-

**Comment by ZaneYork** [comment]
Done

**Comment by ZahurX** [comment]
> Done

Thank:)
