### ISSUE TITLE
Failed to sign in

### ISSUE THREAD

**Issue by Jeeeznutz** [ZaneYork/SMAPI-Android-Installer#291]
![Screenshot_2023-03-24-07-37-03-86_289ce727d0c54b7a6b438eba754ebac7](https://user-images.githubusercontent.com/128757993/227387828-0b763a81-f89d-46ce-b9b8-e6c5522d4e50.jpg)

So I have SV 1.4.5.145 original and already tried to install other versions either the same problem or entering the app(the smapi not the installer) immediately kicks me out

**Comment by Jeeeznutz** [comment]
If you'd like to know which apk I used it's apkmodo's

**Comment by Andremamanks** [comment]
My brother... You're using smapi for 1.4.5.148

**Comment by Andremamanks** [comment]
Try this version of [SMAPI](https://github.com/ZaneYork/SMAPI-Android-Installer/releases/download/v3.7.6.3/SMAPI.Installer_v3.7.6.3.apk) and pair it with Stardew version of 1.4.5.151 (I tried this on android 7-8, the result of android Pie(9) or above may differents)

**Comment by Jeeeznutz** [comment]
Thank you andre that worked

**Comment by Jeeeznutz** [comment]
.
