### ISSUE TITLE
don't do

### ISSUE THREAD

**Issue by Wonder871** [ZaneYork/SMAPI-Android-Installer#295]
hi guys i read all the conversations from a to z
please don't put pressure on zane york

be careful i say this to impatient brats not everyone

**Comment by CHINAisgod** [comment]
Your mother will soon be hit and killed by a car.

**Comment by Wonder871** [comment]
why are you so angry that zane york is not your employee I hope zane york doesn't post the smap😂🤭

**Comment by Wonder871** [comment]
I want to say to everyone here
i only came for smapi before but
I met zane york when i came here and became a follower and i am grateful to him

Thank @ZaneYork

**Comment by Wonder871** [comment]
I'm so sorry my english is bad maybe there is a typo🤭

**Comment by Ze4a8** [comment]
Please stop posting useless issues, no one cares about whatever argument you guys might be having

**Comment by Wonder871** [comment]
@Ze4a8 okey bro soory
