### ISSUE TITLE
Attempt to get length of null array

### ISSUE THREAD

**Issue by NecroNacho** [ZaneYork/SMAPI-Android-Installer#297]
![Screenshot_20230404-121949_SMAPI Installer.jpg](https://user-images.githubusercontent.com/127846077/229686286-4145f97d-3cf1-4cdf-8fdb-3f8e7f58d1ba.jpg)

**Comment by pamelaemaicon** [comment]
O meu tá  dando como versão antiga

**Comment by pamelaemaicon** [comment]
O meu tbm

**Comment by GoingHT** [comment]
Yeah me too

**Comment by haeseull** [comment]
![KakaoTalk_20230404_142212927](https://user-images.githubusercontent.com/126547353/229694428-5184cfb8-9a16-42e5-ab29-7c3b6ecc0b08.jpg)

smapi failed to initialize system.IO.directory not found exceptioncould not find a part of the   path
How do we fix this?

**Comment by yy780** [comment]
Install  SMAPI Installer  apk signature required
In Smapi change the mods location to Android/data/com.zane.stardewvalley/files/Mods
Move the mod you want to use and enjoy now

**Comment by lianmola** [comment]
> ![Screenshot_20230404-121949_SMAPI Installer.jpg](https://user-images.githubusercontent.com/127846077/229686286-4145f97d-3cf1-4cdf-8fdb-3f8e7f58d1ba.jpg)

I had the same error. I uninstalled the game and reinstalled it in google play. That made the app work.

**Comment by yy780** [comment]
> > SMAPI 安装程序文件夹中安装的 apk 文件（需要签名的 apk） 在 SMAPI 中将模组位置更改为 android/data/com.zane.stardewvalley/files/Mods从发射 
> > 我无法访问我的 android/data 文件夹

Mods file location is not fixed
You can change to StardewValley/Mods

**Comment by FansaiKudosai** [comment]
> > ![Screenshot_20230404-121949_SMAPI Installer.jpg](https://user-images.githubusercontent.com/127846077/229686286-4145f97d-3cf1-4cdf-8fdb-3f8e7f58d1ba.jpg)
> 
> I had the same error. I uninstalled the game and reinstalled it in google play. That made the app work.

Hi, can you write me a telegram? t.me/FanKud

**Comment by HwangMetal** [comment]
The stardew valley apk first, then install smapi. Then you can install patched stardew valley from smapi. 

Mods file location still unknown to me.

**Comment by GoingHT** [comment]
![IMG_20230404_041621.jpg](https://user-images.githubusercontent.com/51862338/229730551-e16fdc46-73c0-42f6-9b5c-cb2c0be6a7fa.jpg)

**Comment by HwangMetal** [comment]
![Screenshot_2023-04-04-15-22-45-273_com miui securitycenter](https://user-images.githubusercontent.com/99549585/229732692-ee6e4118-6e34-45d5-a701-7a5184819659.jpg)

**Comment by bagheri76** [comment]
> ![Screenshot_2023-04-04-15-22-45-273_com miui securitycenter](https://user-images.githubusercontent.com/99549585/229732692-ee6e4118-6e34-45d5-a701-7a5184819659.jpg)

pls write how to install step by step tnx

**Comment by Skishe** [comment]
Is it an Android 13 problem?

**Comment by HwangMetal** [comment]
> Is it an Android 13 problem?

I guess so. Android 13 seems trouble with storage permission

**Comment by HwangMetal** [comment]
> > ![Screenshot_2023-04-04-15-22-45-273_com miui securitycenter](https://user-images.githubusercontent.com/99549585/229732692-ee6e4118-6e34-45d5-a701-7a5184819659.jpg)
> 
> pls write how to install step by step tnx

https://github.com/ZaneYork/SMAPI-Android-Installer/issues/297#issuecomment-1495518352

**Comment by FansaiKudosai** [comment]
https://github.com/ZaneYork/SMAPI-Android-Installer/issues/301#issue-1653459704

**Comment by Melissa-bored** [comment]
I've been getting the same error I was so excited to be able to play with mods
It gives me the same error when it's on 44% I put the mods on Zane's folder for mod how to fix this? I understand this happens cuz it's alpha but any solutions?

**Comment by Chezst** [comment]
Hi! I know I'm supposed to add a an error log, but it didn't populate... so here we go: after I finally was able to install smapi cus I was getting the same error as above, when I opened it, this appeared, and I am at a loss on what to do cus I'm definitely not smart in that area. Plz help. Thanks, and blessings!

![Screenshot_20230404_160029](https://user-images.githubusercontent.com/127786634/229908567-3e78693e-c080-4abf-9d88-3e7abb2807a8.jpg)
![Screenshot_20230404_160032](https://user-images.githubusercontent.com/127786634/229908573-4afbc450-37dd-49b8-9148-ec1373fad302.jpg)
![Screenshot_20230404_160036](https://user-images.githubusercontent.com/127786634/229908578-2eefe86d-6b39-4f6c-89b6-f5cd59d1efd6.jpg)
![Screenshot_20230404_160038](https://user-images.githubusercontent.com/127786634/229908583-b0885809-3a2b-43b7-828f-ca4760d0b413.jpg)
![Screenshot_20230404_160041](https://user-images.githubusercontent.com/127786634/229908588-7faa7a49-815e-436b-b047-bb4d2690d3a1.jpg)
![Screenshot_20230404_160045](https://user-images.githubusercontent.com/127786634/229908590-51502166-e31f-44c9-b9b0-81111ad04fa2.jpg)
![Screenshot_20230404_160049](https://user-images.githubusercontent.com/127786634/229908593-cab5a8a0-ac6a-4f9c-8548-c3fa9dd38718.jpg)

**Comment by SemLynn** [comment]
> > ![Screenshot_20230404-121949_SMAPI Installer.jpg](https://user-images.githubusercontent.com/127846077/229686286-4145f97d-3cf1-4cdf-8fdb-3f8e7f58d1ba.jpg)
> 
> I had the same error. I uninstalled the game and reinstalled it in google play. That made the app work.

Didn't work for me at all, idk if its because i downloaded my game from happymod though. Also i'm not even at android 13, i switched this game to my phone specially because of this ._.

**Comment by notnamor** [comment]
Tap the 3 dots on upper right corner, tick the advance patching, go back to main menu ther should be new button called initial, tap that, install afterwards.

**Comment by amgamer69** [comment]
> Tap the 3 dots on upper right corner, tick the advance patching, go back to main menu ther should be new button called initial, tap that, install afterwards.

Thank you i tried that and it worked

**Comment by GoofyGrass** [comment]
> misanaenthusiast

![Screenshot_2023-06-05-18-09-11-81_289ce727d0c54b7a6b438eba754ebac7](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/130267399/c894baad-0ae4-4565-bd38-89772163c435)
 It shows this error, please help
