### ISSUE TITLE
People who managed to install the new version

### ISSUE THREAD

**Issue by FansaiKudosai** [ZaneYork/SMAPI-Android-Installer#298]
People who managed to install a new version of smapi, can you write to me in telegram? t.me/FanKud

**Comment by Chara66** [comment]
Hm anyone there.?

**Comment by FansaiKudosai** [comment]
When someone writes I will notify you

**Comment by HwangMetal** [comment]
I manage to install patched one/smapi version. But not yet install the mods

**Comment by FansaiKudosai** [comment]
https://github.com/ZaneYork/SMAPI-Android-Installer/issues/301#issue-1653459704
