### ISSUE TITLE
xnb file load

### ISSUE THREAD

**Issue by wally232** [ZaneYork/SMAPI-Android-Installer#3]
Custom Localization Mod

In the Content folder
The Characters folder was created.
An Farmer folder was created inside the Characters folder.
You have inserted xnb-related files into the Farmer folder.

The xnb file in the Farmer folder does not seem to be applied in the game.

accessories.xnb
hairstyles.xnb

The above two files are not applicable.

**Comment by ZaneYork** [comment]
It might be broken xnb file? Could you provide these xnb files? I'll test it.

**Comment by wally232** [comment]
The file was mailed to you

There are other things that don't apply.

I'm going to run more tests.

**Comment by wally232** [comment]
I think localization is only possible in Chinese.

To apply Korean..
How do I configure the config?

There are some things that cannot be set in Chinese.
furniture.xnb

I am using a translator.
I'm sorry.

**Comment by ZaneYork** [comment]
For custom localization support, you can lookup [this repo](https://github.com/ZaneYork/SDV_CustomLocalization) for some instructions.The release page contains a demo locale pack of Chinese, for another locale you may needs to use enum code 13 or bigger.

**Comment by ZaneYork** [comment]
> The file was mailed to you
> 
> There are other things that don't apply.
> 
> I'm going to run more tests.

I had not received the email, did you sent to a wrong address?

**Comment by wally232** [comment]
The game was played without changing the localization code.
It all works well.
But there are some things that are not applicable.
The files below are not applied.
The other files were well applied.
Cursors.ko-KR.xnb
Cursors.xnb
MobileAtlas_manually_made.xnb
accessories.xnb
hairstyles.xnb
furniture.xnb
furniture.ko-KR.xnb
tools.xnb

Other files are still being tested.

=================================
The following Korean-related files have also been applied:
All other Korean-related files are also well applicable.
All but the above files apply.
spring_outdoorsTileSheet.ko-KR.xnb
spring_twon.ko-KR.xnb
TitleButtons.ko-KR.xnb

**Comment by wally232** [comment]
https://drive.google.com/drive/folders/1C2pQe75oEdyeGoQ4yh0Aow5FixhtAwsK

In the update to SMAPI above,

Fix support for Stardew Valley of Samsung version

I'm curious about this.
Are you talking about the Galaxy Store State Valley?

SMAPI Installer_v1.3.5.apk
The cafe member tested it but it is not installed.

Previous SMDorid SMAPI supported other phones

**Comment by ZaneYork** [comment]
Still&nbsp; not available? Sorry, but I did not have the Stardew Valley from Galaxy Store, could you send it to me for test suppose?

**Comment by wally232** [comment]
I mailed it to you.

**Comment by ZaneYork** [comment]
Fixed in latest 1.3.6 version, you can get it from github right now or wait for Google Play&nbsp;



---Original---
