### ISSUE TITLE
Smapi needs update

### ISSUE THREAD

**Issue by samwise3377** [ZaneYork/SMAPI-Android-Installer#30]
Hello, smapi mobile needs an update to version 3.7.2 mods like entorax framework (mod lib) are not working in the current version of android smapi

**Comment by ZaneYork** [comment]
I'll upgrade it to 3.7.2 later, the  Entorax Framework is not compatible with Android version, at lease not compatible in upcoming next release

**Comment by LuxiMalikSuzumori** [comment]
Would really like this update for android asap. My smapi keeps crashing because of all the errors of my mods not working because they require an update

**Comment by LuxiMalikSuzumori** [comment]
do you have an idea as to when it would be available?

**Comment by ZaneYork** [comment]
When I have spare time, maybe this weekend

**Comment by LuxiMalikSuzumori** [comment]
that would be greatly appreciated! Sorry if putting you under pressure ^^"

**Comment by droy001** [comment]
Thank you Zane! We really appreciate it.  I just discovered SDV and mods.  I can't believe that you are the only one that is keeping this afloat.  It's such a gift being able to play this game on android.

**Comment by doloresx** [comment]
We look forward to your new version very much.  Thank you！

**Comment by LuxiMalikSuzumori** [comment]
My mods keep giving me errors saying I need to update SMAPI. Really need this updated for android asap please

**Comment by LuxiMalikSuzumori** [comment]
TMXL and PyTK cant update until android does. which means most mods wont work until it updates

**Comment by ZaneYork** [comment]
Upgrated, and the TMXL will fixed in next release, this is the [pre-release](https://drive.google.com/file/d/1XQv4PBvrP-w7EwkgGzmkC645tehcSioe/view?usp=sharing) for testing.

**Comment by LuxiMalikSuzumori** [comment]
thank you!
