### ISSUE TITLE
CJB Cheats Menu not compatible

### ISSUE THREAD

**Issue by Runningham9** [ZaneYork/SMAPI-Android-Installer#317]
![Screenshot_2023-04-06-16-36-15-758_com.mxtech.videoplayer.ad.jpg](https://user-images.githubusercontent.com/130043644/230380022-2431a3bb-4c4b-44b7-9b83-82c0d1785373.jpg)

**Comment by dmitriyromanyuk** [comment]
At the moment, most of the mods just don't work on the alpha version, so you need to wait

**Comment by Runningham9** [comment]
> At the moment, most of the mods just don't work on the alpha version, so you need to wait

Can you share what mods that is work in alpha?

**Comment by lulateamo** [comment]
can someone analyze my smapi log and see what is wrong?  https://smapi.io/log/d3745806924c4e378a68265e45dab384

**Comment by disguy900** [comment]
![Screenshot_2023-09-15-06-42-11-13_b455cd2e68c7bcd1c56b48948a696206](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/145080270/7b9f109a-9a61-4be7-89c3-db659967ccef)
Can anyone give me a compatible cheat menu
