### ISSUE TITLE
Co-op Menu is removed.

### ISSUE THREAD

**Issue by TMThong** [ZaneYork/SMAPI-Android-Installer#318]
Hi I am Multiplayer Mod developer for android users.  But when the game is updated the classes (CoopMenu, CoopGameMenu , CoopMenuMobile) in the StardewValley.Menus space have been removed. I hope the next update you can write 1 more class to rewrite the missing parts.  Or if you can't do it, I have to get the code from the PC version to the Android version.

**Comment by Handyfff** [comment]
Are you seriously trying to do that? That will take some heavy effort and a lot of time. So I hope you success in this mission.

**Comment by bagheri76** [comment]
> Are you seriously trying to do that? That will take some heavy effort and a lot of time. So I hope you success in this mission.

yes im the fan of thong's works he was made multiplayer mod for 1.4 mobile version. and now we are waiting for update for 1.5.
wish good luck and tnx for your efforts @ZaneYork and @TMThong ❤️❤️

**Comment by TMThong** [comment]
> Are you seriously trying to do that? That will take some heavy effort and a lot of time. So I hope you success in this mission.

Do not worry.  I just update and fix my mod.  Some classes have been deleted so I need help.  Thank you

**Comment by Skishe** [comment]
> > Are you seriously trying to do that? That will take some heavy effort and a lot of time. So I hope you success in this mission.
> 
> Do not worry. I just update and fix my mod. Some classes have been deleted so I need help. Thank you

Isn't it a mobile Port problem than smapi?

**Comment by TMThong** [comment]
> > > Are you seriously trying to do that? That will take some heavy effort and a lot of time. So I hope you success in this mission.
> > 
> > 
> > Do not worry. I just update and fix my mod. Some classes have been deleted so I need help. Thank you
> 
> Isn't it a 1.5 mobile Port problem than smapi?

Yes, but since I only need the menu coop classes.  Because of the interface it is really suitable for mobile.  If I get the code from the PC version.  I think it fits, that's all.

**Comment by TMThong** [comment]
Will use classes if they are added.
