### ISSUE TITLE
Failed to process zip entry

### ISSUE THREAD

**Issue by RUNNEARS** [ZaneYork/SMAPI-Android-Installer#339]
![Screenshot_2023-04-12-15-10-11-739_com zane smapiinstaller](https://user-images.githubusercontent.com/119922628/231396559-73e0ed01-cc03-4375-8be1-d719840f4ecf.jpg)
Hello, I am having some issues with installing SMAPI. The issue is stated in the following picture.

**Comment by LilimVipera** [comment]
Yeah, that seems to be a common error. Look at the other issues since yesterday, it's mostly this. But until now, I haven't seen any solutions, so I just went back to the version before (3.18.2.1Alpha). Though you can't "update", you need to uninstall 3.18.2.2 first

(But just as a friendly reminder: before posting a new issue it's recommended to first look if your problem is already posted. Cause imagine the modder/programmer had to answer each user seperately...)

**Comment by Runningham9** [comment]
> Yeah, that seems to be a common error. Look at the other issues since yesterday, it's mostly this. But until now, I haven't seen any solutions, so I just went back to the version before (3.18.2.1Alpha). Though you can't "update", you need to uninstall 3.18.2.2 first
> 
> (But just as a friendly reminder: before posting a new issue it's recommended to first look if your problem is already posted. Cause imagine the modder/programmer had to answer each user seperately...)
> 

Can you give me 3.18.2.1Alpha apk?

**Comment by NoLaw-FR** [comment]
> 

You can find the SMAPI 3.18.2.1_Alpha APK in the assets on the last release, juste keep in mind that this still is a Alpha Pre-release and you should not expect much, nor for it to work, same for the mods, this will probably be more stable once the final version of the installer while be released

**Comment by kitoaltez** [comment]
> ![Screenshot_2023-04-12-15-10-11-739_com zane smapiinstaller](https://user-images.githubusercontent.com/119922628/231396559-73e0ed01-cc03-4375-8be1-d719840f4ecf.jpg) Hello, I am having some issues with installing SMAPI. The issue is stated in the following picture.

Try do mine in #334

**Comment by nexxy110708** [comment]
Someone help me i just need to change the mod path to the Android/stardewvalley but it's keep saying "Please enter the correct path" and now the mod path is on Android/data/com.zane.stardewvalley/mods
