### ISSUE TITLE
TMXL mode is not compatible with the new version of SMAPI.

### ISSUE THREAD

**Issue by wally232** [ZaneYork/SMAPI-Android-Installer#34]
https://smapi.io/log/fd6857959ff249bead585c5001fbbde0

TMXL mode is not compatible with the new version of SMAPI.

SMAPI Android Installer v1.5.9
SMAPI 3.7.3

**Comment by Johnwawet** [comment]
TMXL Mode hasn't worked but TMXL  works just not The build mode which I haven't been able to get it to work in the last 2 versions

**Comment by ZaneYork** [comment]
The TMX Loader add a method reference which Android platform does not have, will fix in next release.
You can try this [pre-release](https://drive.google.com/file/d/1XQv4PBvrP-w7EwkgGzmkC645tehcSioe/view?usp=sharing).

**Comment by Johnwawet** [comment]
I tried the one u posted above but it will not even install and it doesn't write a log but all it says "app can't install"

**Comment by wally232** [comment]
Wow...
We Smapi's got no problem...
TMXL mode is activated.
Thank you very much.

SMAPI Installer 1.5.10_alpha.apk

**Comment by ate0ate** [comment]
That prerelease is working great so far. Thank you for that. I ran into this issue and was able to immediately fix it using that.
