### ISSUE TITLE
Smapi didn't run 

### ISSUE THREAD

**Issue by Lenmiwinks** [ZaneYork/SMAPI-Android-Installer#340]
Sorry to bother, but Idk what to do, I follow all the instructions and still having the same problem, I try uninstalling and reinstalling a couple of times and the problem still ;(
![Screenshot_20230412-022211](https://user-images.githubusercontent.com/125225179/231483193-039f1496-05b8-4816-a914-f03ae0620849.png)
![Screenshot_20230412-020439](https://user-images.githubusercontent.com/125225179/231483208-8c1ef90f-5be0-4385-9791-172f3784aa23.png)

**Comment by speedythehedghog** [comment]
i really need help too :(

**Comment by Chezst** [comment]
Did you follow ALL the instructions on the tutorial? Do you have Android 13 or below? Whats teps did you follow?

**Comment by Lenmiwinks** [comment]
> Did you follow ALL the instructions on the tutorial? Do you have Android 13 or below? Whats teps did you follow?

Hey, I follow all, not once, at least, four times, repeat all the process following the instructions that are in the main page, and, see another's issues and see what were the commons errors that people do on installation and avoided then, I am android 11, I follow this steps:

Download the latest apk package from the Releases page
After it is finished downloading, install it. Then open the SMAPI installer app and hit the install button.
Wait for it to finish, and install the gennerated apk.
Place downloaded mods into the StardewValley/Mods folder on your internal storage.
Open the new SMAPI Stardew Valley app to play the modded version of the game.

I am using a pirated APK, probably, that's the reason it didn't work, I forgot to mention it

Pd: I can buy the game, I am from Venezuela and purchases from Google play are banned in our country ;(

**Comment by Chezst** [comment]
> > Did you follow ALL the instructions on the tutorial? Do you have Android 13 or below? Whats teps did you follow?
> 
> Hey, I follow all, not once, at least, four times, repeat all the process following the instructions that are in the main page, and, see another's issues and see what were the commons errors that people do on installation and avoided then, I am android 11, I follow this steps:
> 
> Download the latest apk package from the Releases page After it is finished downloading, install it. Then open the SMAPI installer app and hit the install button. Wait for it to finish, and install the gennerated apk. Place downloaded mods into the StardewValley/Mods folder on your internal storage. Open the new SMAPI Stardew Valley app to play the modded version of the game.
> 
> I am using a pirated APK, probably, that's the reason it didn't work, I forgot to mention it
> 
> Pd: I can buy the game, I am from Venezuela and purchases from Google play are banned in our country ;(

I'm sorry to hear that /: 

Por cierto, pusiste el folder que hay qje bajar del tutorial que s ellama "com.zane...." dentro del folder llamado "Android/Data"? En ese folder es que iran los Mods que bajes. 

Las instrucciones aparentemente ya no estan pinned en issues, pero el post anda por ahi, ya que el proceso de instalar la version alfa es diferente a instalar el SMAPI normal.

**Comment by Lenmiwinks** [comment]
> > > Did you follow ALL the instructions on the tutorial? Do you have Android 13 or below? Whats teps did you follow?
> > 
> > 
> > Hey, I follow all, not once, at least, four times, repeat all the process following the instructions that are in the main page, and, see another's issues and see what were the commons errors that people do on installation and avoided then, I am android 11, I follow this steps:
> > Download the latest apk package from the Releases page After it is finished downloading, install it. Then open the SMAPI installer app and hit the install button. Wait for it to finish, and install the gennerated apk. Place downloaded mods into the StardewValley/Mods folder on your internal storage. Open the new SMAPI Stardew Valley app to play the modded version of the game.
> > I am using a pirated APK, probably, that's the reason it didn't work, I forgot to mention it
> > Pd: I can buy the game, I am from Venezuela and purchases from Google play are banned in our country ;(
> 
> I'm sorry to hear that /:
> 
> Por cierto, pusiste el folder que hay qje bajar del tutorial que s ellama "com.zane...." dentro del folder llamado "Android/Data"? En ese folder es que iran los Mods que bajes.
> 
> Las instrucciones aparentemente ya no estan pinned en issues, pero el post anda por ahi, ya que el proceso de instalar la version alfa es diferente a instalar el SMAPI normal.

La versión alfa no me funcionó tampoco, lo intenté también unas 3 veces, incluso cuando desapareció el issue, yo tenía el link en el historial así que pude seguir intentado, y nada, simplemente, creo que es incompatible con una apk pirata
