### ISSUE TITLE
Says terminal failed when loading

### ISSUE THREAD

**Issue by Accalia91** [ZaneYork/SMAPI-Android-Installer#35]
I installed the newest smapi last night. It said termainal fail. I uninstall everything reinstall still says it. It still says it 80% of my mods dont work because of the terminal fail issue.
![Screenshot_20200916-220443](https://user-images.githubusercontent.com/71464350/93518483-15cccb00-f8ea-11ea-8580-ddad1905a3a0.jpg)

**Comment by ZaneYork** [comment]
This is not a big deal, the Android platform does not have terminal

**Comment by Accalia91** [comment]
> This is not a big deal, the Android platform does not have terminal

It's never said this before until this update and it doesnt load 80% of the mods and all log errors point to the terminal fail so I'm confused but I deleted everything even my mods to see if it would work so I'll try again and download them all again see what happens I guess

**Comment by Accalia91** [comment]
Yeah I reinstalled all the mods and none of the PPJA packs wanna work so maybe it's a mod problem
