### ISSUE TITLE
Softlock Problems

### ISSUE THREAD

**Issue by Rioshinki** [ZaneYork/SMAPI-Android-Installer#350]
Whenever I go into the building screen placement or Museum donation placement I get softlocked and have to restart the game. I am unable to build the tractor garage because of this and I have to go into normal SV to donate. Does anyone know how to fix this problem?

**Comment by polinxox** [comment]
before you donate or build make sure to switch your control to "tap-to-move & auto-attack"

or activate the control toggle  button as well to make your life easier

**Comment by Rioshinki** [comment]
> before you donate or build make sure to switch your control to "tap-to-move & auto-attack"
> 
> or activate the control toggle button as well to make your life easier

Thank you.
