### ISSUE TITLE
An error occurred in the overridden draw loop: NullReferenceException: Object reference not set to an instance of an object   at StardewModdingAPI.Framework.SGame.DrawImpl  when entering someone else's farm.

### ISSUE THREAD

**Issue by TMThong** [ZaneYork/SMAPI-Android-Installer#358]
Yes, I am doing co-op for android. But the SGame.DrawImpl logic is faulty. I hope it will be fixed.
Logs: https://smapi.io/log/58037888e453439c846aa362b324292d

https://user-images.githubusercontent.com/98743684/233404843-b04fa886-e41a-4d42-ba06-f90b58648091.mp4

**Comment by TMThong** [comment]
> > Yes, I am doing co-op for android. But the SGame.DrawImpl logic is faulty. I hope it will be fixed. Logs: https://smapi.io/log/58037888e453439c846aa362b324292d
> > 2023-04-20.21-45-41.online-video-cutter.com.1.mp4
> 
> Tell me if it finished

Just waiting for this bug to be fixed I will release it.

**Comment by bagheri76** [comment]
@ZaneYork please fix this bug. appreciate a lot 🙏🙏

**Comment by TMThong** [comment]
@bagheri76  , @Abm-MODDER My mod has been released.

**Comment by TMThong** [comment]
Without support anymore, I fixed it myself. This is because the "tapToMove" in the GameLocation class is empty!
