### ISSUE TITLE
Problemas com o download 

### ISSUE THREAD

**Issue by SraSenpai** [ZaneYork/SMAPI-Android-Installer#369]
Quando tento baixar o arquivo mais recente, o SMAPI vem mostrando a versão anterior, 3.7, e não a nova 3.18. está acontecendo com mais alguém?

---------------------------------------------------------------------------------------------

Google translator;

 When I try to download the latest file, SMAPI has been showing the old version, 3.7, not the new 3.18. is it happening to anyone else?

**Comment by iJustGhost** [comment]
It's happening to everyone but don't worry the app actually installs 3.18. @ZaneYork just forgot to change it as he prioritizing SMAPI port inside the patcher app.
Please close this issue.
