### ISSUE TITLE
CJB cheat menu cant scroll down

### ISSUE THREAD

**Issue by xefkha** [ZaneYork/SMAPI-Android-Installer#37]
![Screenshot_2020-09-21-15-33-41](https://user-images.githubusercontent.com/71634435/93747588-1edad680-fc21-11ea-86c6-ea4c7990eea2.png)
I can't scroll down, like the picture above, the cheat menu only appears partially.
I am using android 5. SMAPI 3.7.3, Installer 1.5.9

![Screenshot_2020-09-21-15-47-49](https://user-images.githubusercontent.com/71634435/93748166-015a3c80-fc22-11ea-8f3f-d04345579b32.png)
[Log](https://drive.google.com/file/d/1-1ezAoOElpAUbVpK2IyZ755lrpKZ7Q9u/view?usp=drivesdk) 

Does not fully work properly on android 5?
Or am I missing something?

**Comment by ZaneYork** [comment]
Your screen resolution is too small for display the full cheats menu's scroll bar arrow

**Comment by xefkha** [comment]
ah it turns out like that. I tried changing my screen dpi, and it worked.
![Screenshot_2020-09-25-13-56-29](https://user-images.githubusercontent.com/71634435/94236243-18a56c80-ff37-11ea-908b-fbc0ac2a82b8.png)
