### ISSUE TITLE
"App not installed as package seems to be invalid" Error when installing SMAPI 3.7.6.10

### ISSUE THREAD

**Issue by CoderMonkey1956** [ZaneYork/SMAPI-Android-Installer#373]
Hello! Whenever I try to install version 3.7.6.10 I get an error saying that the package is invalid (I'm on SDV version 1.5.6.39) How could this be fixed?

**Comment by FExMERFFY** [comment]
> Hello! Whenever I try to install version 3.7.6.10 I get an error saying that the package is invalid (I'm on SDV version 1.5.6.39) How could this be fixed?

Hello:) 
Bro you need download a old version of SDV - 1.4 From google and then you only could play with mods

**Comment by CoderMonkey1956** [comment]
How do you download an old version?

**Comment by FExMERFFY** [comment]
> 

Just type in google
Download Stardew Valley 1.4 original
If you have android then you'll download it
If u are IOS user then just wait after ZaneYork updates the smapi

**Comment by GabiProGm** [comment]
Hey! Hi! Hello! 
If you want the 1.5 modded version (even tho not all mods work, check for logs on the issues tab)
This is the version that manages to work:
https://github.com/ZaneYork/SMAPI-Android-Installer/releases/tag/v3.18.2.2

**Comment by Rexconc** [comment]
My problem is similar I'm using smapi v3.18.3.3 which I downloaded from GitHub my Stardew valley is v1.5.6.52 each time I go to my file manager to install my smapi Stardew valley it's keep showing package seems to be invalid
![Uploading Screenshot_20241026-030258.jpg…]()

**Comment by Rexconc** [comment]
I tried but this is what it showed me what should I do please help me🥺
C4.b$a: DISPLAY_NAME column is null
	at C4.b.a(SourceFile:15)
	at z4.d.f0(SourceFile:3)
	at z4.e.f0(SourceFile:3)
	at z4.e.x(SourceFile:11)
	at j4.d.q(SourceFile:93)
	at j4.d.r(SourceFile:1)
	at j4.d.o(SourceFile:1)
	at j4.c.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
