### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Accalia91** [ZaneYork/SMAPI-Android-Installer#38]
It was working fine. But now it constantly crashes
 I've removed all mods to see if it was a mod issue but it's not it continues to crash. Wont even go to the loading screen. Ibe also uninstalled and reinstalled
Ever since this update came out it seems like it doesnt wanna work for me

**Comment by xefkha** [comment]
Android 5? Me crash too, but after disable harmony its work fine.
![Screenshot_2020-09-21-15-47-49](https://user-images.githubusercontent.com/71634435/93837359-006fec00-fcb0-11ea-8837-482b355ae9bd.png)

**Comment by Accalia91** [comment]
> Android 5? Me crash too, but after disable harmony its work fine.
> ![Screenshot_2020-09-21-15-47-49](https://user-images.githubusercontent.com/71634435/93837359-006fec00-fcb0-11ea-8837-482b355ae9bd.png)

I just tried that didnt work still crashing

**Comment by Accalia91** [comment]
Even with the new update you just posted it still crashes. I've posted this 2 days ago with no answers

**Comment by ZaneYork** [comment]
> Even with the new update you just posted it still crashes. I've posted this 2 days ago with no answers

I cant locate the BUG without any error logs, needs more details of the error report such as logcat logs to find out the cause.

**Comment by Accalia91** [comment]
> > Even with the new update you just posted it still crashes. I've posted this 2 days ago with no answers
> 
> I cant locate the BUG without any error logs, needs more details of the error report such as logcat logs to find out the cause.

![Screenshot_20200923-230916_SMAPI Installer](https://user-images.githubusercontent.com/71464350/94103452-f9e98d80-fdf1-11ea-91ef-79f9e641696c.jpg)
That's all it says doesnt really say why and ot constantly crashes on loading idk why it says Martyrpher on it when I download the one from this page so I'm also confused on that

**Comment by Accalia91** [comment]
![Screenshot_20200923-123352_One UI Home](https://user-images.githubusercontent.com/71464350/94103580-3ae1a200-fdf2-11ea-9e90-3cc7b7c76c57.jpg)


I was also able to get this rare as of this.... sometimes it will just crash but sometimes I see this but doesnt let me read it crashes and so i attempted to try ss shot it.

**Comment by ZaneYork** [comment]
Got it, you can delete `StardewModdingAPI.crash.marker` file in `StadewValley/smapi-internal` folder manually to solve this issue. This bug will got fixed in next release

**Comment by Accalia91** [comment]
> Got it, you can delete `StardewModdingAPI.crash.marker` file in `StadewValley/smapi-internal` folder manually to solve this issue. This bug will got fixed in next release

THANK YOU JUST DID IT. thanks for your hard work doing this made my day a bit better after a rough day
