### ISSUE TITLE
Any ETA on release?

### ISSUE THREAD

**Issue by Bufftats** [ZaneYork/SMAPI-Android-Installer#395]
I managed to develop and release 3 full games from when the last time I've checked this out. Any word on release time-frame? Lack of communication with the community is a bad look.

**Comment by GonzaUwU** [comment]
> Logré desarrollar y lanzar 3 juegos completos desde la última vez que revisé esto. ¿Alguna palabra sobre el plazo de lanzamiento? La falta de comunicación con la comunidad es un mal aspecto.

I even graduated and I have a job, even so it gives me time to play video games, it is disrespectful that @ZaneYork Not of any news, I know that he has his life like any person but we have already waited a long time...

**Comment by Rineamanoob** [comment]
> Can't wait anymore? Get a job. Save some money. Buy your own PC. Problem solved.

Right? Asking for an eta is fine but being rude is unnecessary. You don't know what's going on in zane's life. Things happen and real life is more important than a virtual community. He'll do what he can when he can. It's available on pc, and if your 3 games are successful buy a laptop with that money.

**Comment by mhambone** [comment]
> > Logré desarrollar y lanzar 3 juegos completos desde la última vez que revisé esto. ¿Alguna palabra sobre el plazo de lanzamiento? La falta de comunicación con la comunidad es un mal aspecto.
> 
> I even graduated and I have a job, even so it gives me time to play video games, it is disrespectful that @ZaneYork Not of any news, I know that he has his life like any person but we have already waited a long time...

Wow that's so great, why don't you take your very useful job and degree and do it yourself? We're waiting.

**Comment by ZenZenXDz** [comment]
> > Logré desarrollar y lanzar 3 juegos completos desde la última vez que revisé esto. ¿Alguna palabra sobre el plazo de lanzamiento? La falta de comunicación con la comunidad es un mal aspecto.
> 
> I even graduated and I have a job, even so it gives me time to play video games, it is disrespectful that @ZaneYork Not of any news, I know that he has his life like any person but we have already waited a long time...

Then make the update idiot, you're a graduate and you have a job buy a pc, why are you still waiting for the mobile version.

**Comment by Bufftats** [comment]
Closed due to users harassing others. Bans will be handed out accordingly.
