### ISSUE TITLE
Error When Launching SMAPI Android

### ISSUE THREAD

**Issue by CoderMonkey1956** [ZaneYork/SMAPI-Android-Installer#398]
Whenever I try to launch the newest version of SMAPI Android I get this error
![Screenshot_20230614_101453](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/112332729/b6495f76-da6c-4752-b434-044dc68ac818)
How can I fix this? And it only happens on 2nd launch, first launch dossent load mods, and 2nd launch just crashes.

**Comment by kei5687** [comment]
Make sure to follow [this](https://github.com/ZaneYork/SMAPI-Android-Installer/issues/301) when installing SMAPI on your device. Also, this is a pre-release version which means that there's gonna to be a lot of bugs and most of the mods won't work properly (or even work at all).

**Comment by CoderMonkey1956** [comment]
New Android restrictions seem to block that, oh well! I'll just be exited for the new release!

**Comment by CoderMonkey1956** [comment]
Just reopened issue. This started in alpha but has now persisted to the full release. If anyone knows how to fix this please help.

**Comment by CoderMonkey1956** [comment]
Continues to happen in the newest release. Should I just get a steam deck and move on or do this?

**Comment by CoderMonkey1956** [comment]
Solution to the bug: delete old instalation files and force-activate all mods!
