### ISSUE TITLE
Can't open the latest version of smapi on android! 

### ISSUE THREAD

**Issue by bryce29** [ZaneYork/SMAPI-Android-Installer#40]
Why the latest version of smapi installer not working on android , its always says  that its need the latest version to install the smapi stardew valley, but i install the smapi installer 1.6.1 its says that it is updated to 3.7.3 something then when i open it ,the running version of smapi is 3.3.2 , so the smapi stardew  valley will not open.  Can you fix it please ,  thank you in advance .. 
Sorry for inconvenience and my grammar .
Thank you so much! 😊

**Comment by ZaneYork** [comment]
You need click the install button again and reinstall the patched game, or else nothing will changed when you update the app itself

**Comment by bryce29** [comment]
I already did it, but it says that my version of stardew valley is not
1.4.5 but i install my sv on playstore so its already updated, then the
smapi installer says that i need to download a compat, so i download it,
but the available compat there is 1.4.4 so if i intall then extract ,the
app is always says that my version is 1.4.4 sv it needs the latest version.
Please help me. Thank you so much

**Comment by ZaneYork** [comment]
That is, the latest version of SDV is 1.4.5.145, yours are outdated

**Comment by bryce29** [comment]
So i need to uninstall then install the latest version?
Okay i try again, thank you so much for your help, can i ask again if i
have a question, sorry for bothering you ,i know that your busy, thank you
so much ❤

**Comment by ZaneYork** [comment]
Legacy support had been updated in latest 1.6.2 version
