### ISSUE TITLE
I can't install smapi 

### ISSUE THREAD

**Issue by Vitorian1** [ZaneYork/SMAPI-Android-Installer#402]
![Screenshot_20230626_130927_SMAPI Installer](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/137813368/9e817ad6-6f27-4db4-8c76-7054b1a01518)
this message appears when I click to install

**Comment by kasuno011** [comment]
Delete the previous stardew valley app created by the smapi installer, then reinstall.

**Comment by Vitorian1** [comment]
where is this app created by smapi?

**Comment by Vitorian1** [comment]
![Screenshot_20230626_152839_My Files](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/137813368/b430394d-bb05-4fc6-8443-65077aa14bb2)
this? because when I delete this and click to install, it reappears

**Comment by kasuno011** [comment]
No the SMAPI Stardew Valley app in your list of apps. The app you run to play the modded game. If you have left the app there that was made by the older version of the SMAPI installer it may give you that error, for me deleting the old app fixed it.

**Comment by Vitorian1** [comment]
aaa thank you for your time, unfortunately mine is another problem <3

**Comment by anonymus177** [comment]
Have you bought the game legally? Reportedly, it does not work with pirated versions.

**Comment by Vitorian1** [comment]
I went to try it on my other device and I got it, thanks guys for the tips
