### ISSUE TITLE
No issue, just a huge Thank You!

### ISSUE THREAD

**Issue by NalgeneOrange** [ZaneYork/SMAPI-Android-Installer#404]
I installed this on a freshly power washed Chromebook and it works!   I have only tried one mod so far, Automatic Gates, and that works perfectly.   I am excited to see what other mods will work. 

Thank you SO MUCH for your hard work on this.  It really means a lot that you took the time to put this update out for all of us who love this game and play it on the mobile platform.

**Comment by AozoraDev** [comment]
I'm glad you enjoyed this...

But this is not how issue on Github work.
This is not the place to appreciate work, but to report problems.

So please close this issue.

**Comment by NalgeneOrange** [comment]
Thank you! :)
