### ISSUE TITLE
Can anyone share the smapi-internal and mods folder!! Please

### ISSUE THREAD

**Issue by Handyfff** [ZaneYork/SMAPI-Android-Installer#407]
This is to the people who bought the game. We can't work it on pirated version. Turns out if you patch the Johnny Depp version smapi does not copy all of it's files and DLLs. It leads to red errors and does not start. So please help us and share those 2 folders. They don't have any private data.

**Comment by shinei29** [comment]
@Handyfff Download the installer again now, just by clicking on install, the smapi is installed with the folders.

**Comment by Handyfff** [comment]
Thanks, it's fixed now. It works with both versions!
