### ISSUE TITLE
How do I fix this "Failed to process zip entry 'VirtualKeyboard/manifest.json with action z9.j$a@46c723"

### ISSUE THREAD

**Issue by Melonieei** [ZaneYork/SMAPI-Android-Installer#408]
![Screenshot_2023-06-27-12-21-29-202_com zane smapiinstaller](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/137858514/272b0737-2801-439b-ab33-debc16e7ea28)

I keep getting this

**Comment by huggh** [comment]
same here
