### ISSUE TITLE
Shop Tile Framework Error

### ISSUE THREAD

**Issue by wally232** [ZaneYork/SMAPI-Android-Installer#41]
https://smapi.io/log/dfe380eb79474d829588ef355c22f97b

Shop Tile Framework Error
There was no problem in the previous version...
In the latest SMAPII get an error.

**Comment by ZaneYork** [comment]
Here is a [pre-release](https://drive.google.com/file/d/1DeMDerM5Fbf3pnHhQ0bjq32lw4SslUf-/view?usp=sharing) for this bug, you can try it.

**Comment by HalfEnder776** [comment]
Don't know if you know this but might as well comment that one of the updates broke shop tile framework I cannot access any shops that use this mod

**Comment by ZaneYork** [comment]
Could you please provide the error log for  this?

**Comment by HalfEnder776** [comment]
I don't really know how to do that but this appears to be a well known issue, here's a picture from the mod I was using (PPJA shop)
![Uploading Screenshot_20200929-224434_Samsung Internet.jpg…]()

**Comment by HalfEnder776** [comment]
OK I checked the console but there was no errors

**Comment by ZaneYork** [comment]
> OK I checked the console but there was no errors

I test it again, it works fine on my device, make sure you are using the latest 1.6.2 version of install and the SMAPI version is 3.7.3.3

**Comment by HalfEnder776** [comment]
I believe I updated it but I'll try again, knowing me I'm probably doing something stupid, when I first had this issue I realized I didn't even have shop tile framework installed, then I tried it again only for it to still not work, I noticed the bug in the comments and relised the new SMAPI update should fix it, still didn't work, then I created this comment. After that I found out the shop tile framework mod was inside a folder so it wasn't even installed. Considering my track record this bug is probably fixed and I'm doing something very very dumb, sorry for wasting your time android modding is great.

**Comment by HalfEnder776** [comment]
OK I really don't know why it won't work at this point.. here is a video that shows me unable to access the shop along with my console which shows that my SMAPI version is 3.7.3.3

**Comment by ZaneYork** [comment]
Maybe you should take a look at StardewVally/ErrorLogs folder for more trace details, send the error log to https://smapi.io/log if possible and paste the url of uploaded logs here



---Original---

**Comment by HalfEnder776** [comment]
Here seems I didn't send the video https://streamable.com/k5289i

Also ill have a look thx

**Comment by HalfEnder776** [comment]
Ok here is the link to the log parser https://smapi.io/log/32f71f29e17a487ca168b2f318e9fc1f

The only red error is from custom music strange this is that I only get that error sometimes while booting up the game so I doubt its the cause of my issue

**Comment by ZaneYork** [comment]
Yes

> Ok here is the link to the log parser https://smapi.io/log/32f71f29e17a487ca168b2f318e9fc1f
> 
> The only red error is from custom music, strange thisng is that I only get that error sometimes while booting up the game so I doubt its the cause of my issue

Yes, this bug still exists in latest 1.6.2 vwrsion

**Comment by ZaneYork** [comment]
> Ok here is the link to the log parser https://smapi.io/log/32f71f29e17a487ca168b2f318e9fc1f
> 
> The only red error is from custom music, strange thisng is that I only get that error sometimes while booting up the game so I doubt its the cause of my issue

Fixed in latest 1.6.3 version, you can check it

**Comment by wally232** [comment]
Thank you.
It's settled.
The mode is working without a problem.
