### ISSUE TITLE
CJB cheat menu bugged and CJB item spawner gives error

### ISSUE THREAD

**Issue by Heco-o** [ZaneYork/SMAPI-Android-Installer#412]
CJB cheat menu doesn't give any error while loading but it doesn't work or shows empty in the menu.
![Screenshot_20230627-190507](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/99784203/3a50acf6-8bf8-4b6e-abfd-d02a44dd1a27)
![Screenshot_20230627-190525](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/99784203/7687b2c7-6280-467d-902b-b232c1c312b2)
On the other hand, CJB item spawner give some errors
![Screenshot_20230627-190748](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/99784203/fb1e3a0d-d31b-47e8-95af-94b48df42bf8)
Even if Zane probably said not to pull out issues about mod but i still did just in case he sees this issue 😓
These 2 CJB mods are probably the best when it's about cheating so i had to pull out this issues

**Comment by AozoraDev** [comment]
> Many of mods may not works, dont post issue to request mods compat. I'll try to fix some of essential mods if it possible when I have spare time

Like it said here, many mods still not work right now...
So don't be stubborn and stay patient waiting for the next update.

And please close this issue.

**Comment by Septiyan125** [comment]
Pathoschild said :
Does this mod work on Android?
Not currently. It's affected by a bug in SMAPI on Android which breaks many other mods too. It's already been reported, so hopefully it'll be fixed in upcoming SMAPI updates on Android.

**Comment by Septiyan125** [comment]
I think maybe we should wait for the SMAPI update

**Comment by Heco-o** [comment]
Welp it can't be helped then
