### ISSUE TITLE
Need help with a multiplayer framework

### ISSUE THREAD

**Issue by TMThong** [ZaneYork/SMAPI-Android-Installer#433]
I created a Mod that helps mobile players play together using the lidgren-network library. However SLidgrenClient and SLidgrenServer are removed from the Mobile SMAPI. I need you to help me re-add these layers. Thanks for paying attention. @ZaneYork
```
internal class SLidgrenClient : LidgrenClient
internal class SLidgrenServer : LidgrenServer
```
[My repo](https://github.com/TMThong/Stardew-Mods/tree/master/MultiplayerMod)

**Comment by 1523006317** [comment]
Great multiplayer mod authors, we love your mod very much, hope your mod is updated more and more perfectly, let me comment to support you  🌹@TMThong
