### ISSUE TITLE
Working mods with smapi v3.18.3.1

### ISSUE THREAD

**Issue by Caeljin** [ZaneYork/SMAPI-Android-Installer#435]
Edit : Only the log since the screenshots do not help 😅
Using a Galaxy J8 and here the log of the mods that work with my device
- 55 mods
- Log link update (Jul 8) 
https://smapi.io/log/97df548266244d91a55023ec340044a3
- Edit 1:Using the new smapi v3.18.3.2 and all the mods still working well (Jul 9)
https://smapi.io/log/e4d09cda70224e899a7cae6e24a27967
- Edit 2: Idk if was testing spacecore mods or using the savegame from the previous version but all the items in the museum collection resetted, only the display items but not the count (i hope) 🤭

**Comment by tjelite1986** [comment]
Can you upload the log file here it will be easier to read 

https://smapi.io/log

**Comment by valera999** [comment]
А мод идёт на чит меню

**Comment by thechickenmoo** [comment]
Bless you. Was looking for some sort of list people had tested. I haven't used mods in a long time and I didn't want to start throwing them in if they just weren't compatible at all.

**Comment by Caeljin** [comment]
Updating other post
