### ISSUE TITLE
Entoarox Framework Mods error

### ISSUE THREAD

**Issue by wally232** [ZaneYork/SMAPI-Android-Installer#44]
https://smapi.io/log/d4b10e343a5642398493bdefdbb0c800

This mode also did not work with previous SMAPIs.
Is this mode no longer compatible with mobile SMAPI?

**Comment by ZaneYork** [comment]
Is this mod works in any previous version before SMAPI 3.7 ? I'm sure this mod will cause some problem and did not make compat logic for this mod, so I was suprised that sounds like this mod may works in earlier version?



---Original---

**Comment by wally232** [comment]
Also in version 3.6.2
It didn't work.
It does not work with the current new version of SMAPI.

**Comment by ZaneYork** [comment]
This framework needs to write some code for moblie platform to deal with the difference of serilization logic.This can not be fixed in SMAPI side, I'll try to find out the way for it when I have enough spare time, without a due date, do not expect too much about this.

**Comment by wally232** [comment]
Thank you..
