### ISSUE TITLE
App not installed. 

### ISSUE THREAD

**Issue by Katnissfwuffkin** [ZaneYork/SMAPI-Android-Installer#444]
I'm getting this error when I try to install can anyone help? I downloaded smapi and when I open it it prompts me to install and that's when this error happens. 
![Screenshot_20230705-093503](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/138705882/5b8c9d91-ce2b-4054-8293-ad6976d7c66a)

**Comment by mike10101011** [comment]
I had this same issue yesterday. Make sure you are using the right installer. Looks like you're doing 3.7.xx when it should be 3.18.xx.

**Comment by Katnissfwuffkin** [comment]
> I had this same issue yesterday. Make sure you are using the right installer. Looks like you're doing 3.7.xx when it should be 3.18.xx.

Where can I find that one? When I go to code on here it only gives me the 3.7 version 
![Uploading Screenshot_20230705-112935.png…]()

**Comment by Katnissfwuffkin** [comment]
> I had this same issue yesterday. Make sure you are using the right installer. Looks like you're doing 3.7.xx when it should be 3.18.xx.

Just kidding. I found it and used that and it worked. When I open sdv through smapi though it has no saved games. The guide says to open it through smapi. Any ideas?
