### ISSUE TITLE
For some reason smapi doesn't have the mods folder

### ISSUE THREAD

**Issue by BilsCaii** [ZaneYork/SMAPI-Android-Installer#453]
![Screenshot_20230708-105546_ZArchiver](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/138986366/20ccc44b-8632-4e6a-b319-5848c5a9ec8d)

**Comment by CookieHug** [comment]
Just create new folder "Mode" In there

**Comment by CookieHug** [comment]
I mean "Mods"

**Comment by lulateamo** [comment]
Can someone send me the zane zip file?
