### ISSUE TITLE
Is SpaceCore working now?

### ISSUE THREAD

**Issue by anonymus177** [ZaneYork/SMAPI-Android-Installer#455]
It seems the latest patch was supposed to fix the serialization error with SpaceCore, but after uninstalling the previous Android SMAPI and installing the version from today, it still shows a serialization error for me. Does it work for anybody yet?

I don't mind waiting at all, just curious if anybody managed to get it working and If I was doing anything wrong.

**Comment by anonymus177** [comment]
Or perhaps it works DESPITE the error? I have not checked that.

**Comment by 3Negativ3** [comment]
Same here. It's giving me a lot of errors

**Comment by Rajarshi393** [comment]
Working now

**Comment by Rajarshi393** [comment]
Its fixed

**Comment by anonymus177** [comment]
> Its fixed

Could you elaborate a bit? I downloaded newest SMAPI Android (from 12 hours ago), newest SpaceCore and I'm still getting an error. You did the same and have no error whatsoever in the console?

**Comment by ArthurWarden** [comment]
I was using the smapi that came a few weeks ago and the mods i was using were showing errors yet they were working. Why not get a spacecore dependent mod and see if it works?
