### ISSUE TITLE
StringSplitOptions.TrimEntries does not work as expected on Android

### ISSUE THREAD

**Issue by atravita-mods** [ZaneYork/SMAPI-Android-Installer#461]
Passing StringSplitOptions.TrimEntries to string.Split does nothing on Android.

On PC, the attached test mod correctly produces
![image](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/94934860/2b3f9245-9a4e-4267-95c2-79379a50542f)

On Android, this produces
![image](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/94934860/5b2ca90a-ca44-4a94-a622-04059c7fda0a)

This currently breaks AllowedValues on ContentPatcher, for example.

[MobileTest 0.1.0.zip](https://github.com/ZaneYork/SMAPI-Android-Installer/files/11995525/MobileTest.0.1.0.zip)

source: https://gist.github.com/atravita-mods/5dda327a7b9476ba5ce1b3a386883e59

**Comment by ZaneYork** [comment]
Fixed in upcoming 3.18.3.3
