### ISSUE TITLE
Game freezes?

### ISSUE THREAD

**Issue by KaylaHunther** [ZaneYork/SMAPI-Android-Installer#467]
the game freezes whenever I go to the building mode, donation mode and dye mode
and I always ended up having to restart the game
sometimes the game just straight up crashed when I open the dye menu 
I even tried deleting all my mods, resetting the game entirely to see maybe it was an issue with the mods but nothing worked
What should I do?

**Comment by MadTurbate** [comment]
same error with mine, I used CJB mods, hope it gets fixed next update.

**Comment by Caeljin** [comment]
Using mods that use spacecore freeze the game sometimes in events and changing maps here (rarely)

**Comment by KaylaHunther** [comment]
> Using mods that use spacecore freeze the game sometimes in events and changing maps here (rarely)

I'm sorry but what's spacecore? I'm very new to Stardew and modding so there's a lot I don't know

**Comment by esih351h** [comment]
Like ZaneYork said this still have some compatibility issue so if u didn't want encounter some error make it mod that didn't add new to original game btw spacecore is like the brain for some mods so if your brain error and will do the same to the body

**Comment by 3Negativ3** [comment]
Are you using joystick controls? You just have to switch to full touchscreen mode before you go to any of those modes. That should fix your problem

**Comment by Skishe** [comment]
Oh i know this one... This is not a mod problem but rather a cursor problem. This was also present in 1.3 stardew android.

It was pretty easy to trigger although i forgot how to do it now. To fix it, you just had to open the console through virtual keyboard then go back.
