### ISSUE TITLE
Working modlist with the v3.18.3.2 release

### ISSUE THREAD

**Issue by Caeljin** [ZaneYork/SMAPI-Android-Installer#468]
-The only error here is from the spacecore and can make the game unstable if you choose to use but the other mods run without errors 
-Here the log of the working mods i use
https://smapi.io/log/0d884ca3e11e475db421bfc4287bf4f0
Edit1: I used a save from the version 3.18.3.1, the museum collection resetted. Idk if was the save or a spacecore mod i tried that caused this. 
- Adventurer's Guild Expanded (working well, just do not try to marry the new girl npc 😅)
- BetterTappers 👌
- Magic (Seems to work but idk how to Hold a combination of keys with the virtual keyboard to cast magic, maybe not work with mobile)
-  Personal anvil (all work until you try to use the anvil - nothing happens)

**Comment by Zencee** [comment]
have you tried the quest framework? i couldn't make it run with npc adventures

**Comment by Caeljin** [comment]
Seems to not run yet, same as the producer framework 😞

**Comment by esih351h** [comment]
For Magic u can try use Mobile Phone Mods or use VolumeUp/Down the only button available on most mobile

**Comment by Skishe** [comment]
> -The only error here is from the spacecore and can make the game unstable if you choose to use but the other mods run without errors -Here the log of the working mods i use https://smapi.io/log/0d884ca3e11e475db421bfc4287bf4f0 Edit1: I used a save from the version 3.18.3.1, the museum collection resetted. Idk if was the save or a spacecore mod i tried that caused this.
> 
> * Adventurer's Guild Expanded (working well, just do not try to marry the new girl npc 😅)
> * BetterTappers 👌
> * Magic (Seems to work but idk how to Hold a combination of keys with the virtual keyboard to cast magic, maybe not work with mobile)
> * Personal anvil (all work until you try to use the anvil - nothing happens)

Back in 1.4 stardew... I changed the hotkeys in Magic through the configs and it worked flawlessly.

Idk if 1.5 stardew functions the same way as 1.4 stardew but... Back in 1.4 stardew, There is actually a mouse cursor albeit invisible. It can be seen through Automate mod UI.

**Comment by Caeljin** [comment]
New update
Looks like better start a new game 🤭
I will only use cjb cheat to obtain 100 golden walnuts later 😼

**Comment by Caeljin** [comment]
New list with the new update
