### ISSUE TITLE
My game keeps crashing when I load my saves

### ISSUE THREAD

**Issue by Deijiya** [ZaneYork/SMAPI-Android-Installer#480]
As the title says, my game keeps crashing whenever I try to load my saves. I don't understand what causes it. I tried to remove mods. But it even crashes mods with no errors? I don't really understand what am I supposed to do?? Can someone really help? 

https://smapi.io/log/ad9a73ec26454137bed49d18e7b3b20b

**Comment by Caeljin** [comment]
Maybe the save was corrupted, that is the problem with only 1 save. Idk the process of the creation of emergency saves. Better keep always a manual zipped backup each day

**Comment by Deijiya** [comment]
> 

Thank you so much!
