### ISSUE TITLE
Spacecore not working

### ISSUE THREAD

**Issue by VWRBUG07** [ZaneYork/SMAPI-Android-Installer#481]
![Screenshot_20230712-144618](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/78944996/4d68ee87-b6ed-45be-9c1b-43eb4513f41c)
![Screenshot_20230712-144650](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/78944996/33ec802b-fd26-4f09-b061-129ea6c05e51)
This is what pops up in my smapi log can anyone help?

**Comment by GonzaUwU** [comment]
> ![Captura de pantalla_20230712-144618](https://user-images.githubusercontent.com/78944996/253108388-4d68ee87-b6ed-45be-9c1b-43eb4513f41c.jpg) ![Captura de pantalla_20230712-144650](https://user-images.githubusercontent.com/78944996/253108401-33ec802b-fd26-4f09-b061-129ea6c05e51.jpg) Esto es lo que aparece en mi registro de smapi, ¿alguien puede ayudarme?

If it works, just ignore that red text, I loaded the dynamic assets mod that occupies spacecore, just ignore those errors because if it works :)

**Comment by VWRBUG07** [comment]
But it doesn't that's the thing stuff won't load because and it causes my game to crash

**Comment by GonzaUwU** [comment]
> Pero no es así porque las cosas no se cargan y hace que mi juego se bloquee.

Well, I think that depends on the mobile and its Android version, because I get those spacecore errors but the Json Assets , furniture and dynamic assets mods still load me

**Comment by HwangMetal** [comment]
> ![Screenshot_20230712-144618](https://user-images.githubusercontent.com/78944996/253108388-4d68ee87-b6ed-45be-9c1b-43eb4513f41c.jpg) ![Screenshot_20230712-144650](https://user-images.githubusercontent.com/78944996/253108401-33ec802b-fd26-4f09-b061-129ea6c05e51.jpg) This is what pops up in my smapi log can anyone help?

Spacecore is working. But other mods that depends on spacecore not yet compatible with latest version of smapi Android. We have to push the mods author/creator to update according to Android version smapi in Nexus.

**Comment by Zencee** [comment]
For now don't use spacecore.. reportedly there had been many bugs on players save file if you use it. The most common one is all the donated artifacts you give to the museum will all be lost the next time you restart the game, the other bug will suddenly remove your save file entirely. Just wait for the new update
