### ISSUE TITLE
Stardew valley expanded works and it's great

### ISSUE THREAD

**Issue by dmitriyromanyuk** [ZaneYork/SMAPI-Android-Installer#487]
![Screenshot_2023-07-14-16-55-50-225_com zane stardewvalley](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/61154383/63b07b30-112c-469c-82cb-7cdfbf669bfa)
I decided to test Expanded on the latest version of smapi and everything seems to be working. Even the spacecore error does not interfere, which is surprising :)

**Comment by Zebov** [comment]
> ![Screenshot_2023-07-14-16-55-50-225_com zane stardewvalley](https://user-images.githubusercontent.com/61154383/253564277-63b07b30-112c-469c-82cb-7cdfbf669bfa.jpg) I decided to test Expanded on the latest version of smapi and everything seems to be working. Even the spacecore error does not interfere, which is surprising :)

I thought the same thing, but my museum doesn't save anything. Lost a couple dwarf scrolls, but otherwise found out soon enough.

**Comment by Paraliis** [comment]
How? When i tested it i couldnt go to the areas sve added.

**Comment by RakanIV** [comment]
Bro what! how? i tested it  im just stuck in grandpa's farm

**Comment by dmitriyromanyuk** [comment]
> Bro what! how? i tested it im just stuck in grandpa's farm

Yes, there are still bugs, including the inability to go to the location, but I was just glad that the game somehow started.
