### ISSUE TITLE
Automate display error

### ISSUE THREAD

**Issue by mspzyzh** [ZaneYork/SMAPI-Android-Installer#496]
![Screenshot](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/13333156/c08724b0-2274-47c7-8a7f-e362ce9de1c6)
automation overlay cannot display

**Comment by Zencee** [comment]
Maybe change the version of automate you're using. In my case, it seems to be working fine. This is the version i've been using https://www.nexusmods.com/stardewvalley/mods/1063?tab=files&file_id=54166

![Screenshot_2023-07-16-18-50-50-899_com zane stardewvalley](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/129819788/93e43959-2816-481a-b8f1-b0a0153f634d)

**Comment by mspzyzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Caeljin** [comment]
The 1.7.5 and 1.6 works but one time the 1.7.5 caused one error (using the 1.6 atm)

**Comment by mspzyzh** [comment]
images.githubusercontent.com/129819788/2537

**Comment by mspzyzh** [comment]
> Maybe change the version of automate you're using. In my case, it seems to be working fine. This is the version i've been using https://www.nexusmods.com/stardewvalley/mods/1063?tab=files&file_id=54166
> 
> ![Screenshot_2023-07-16-18-50-50-899_com zane stardewvalley](https://user-images.githubusercontent.com/129819788/253799667-93e43959-2816-481a-b8f1-b0a0153f634d.jpg)

Thanks,1.27.0 is OK
