### ISSUE TITLE
Newtonsoft error 

### ISSUE THREAD

**Issue by EiKQr** [ZaneYork/SMAPI-Android-Installer#498]
![Screenshot_2023-07-18-15-25-54-839_com zane stardewvalley](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/129840603/09ba7548-241f-4db8-a13e-ca2acd7f11b7)

Any idea what newtonsoft is and why it gives error? 
I had thought it was due to some mod but no, it's a clean installation 

I don't know if it has something to do with it but my base version of Stardew Valley is 1.5.6.39

**Comment by EiKQr** [comment]
The game only opens when I delete or rename the "smapi-internal" folder in the path I select but it doesn't load any mods

**Comment by EiKQr** [comment]
It worked with this file but it only loads the keyboard and console mod https://github.com/ZaneYork/SMAPI-Android-Installer/files/11144397/com.zane.stardewvalley.zip

**Comment by EiKQr** [comment]
It worked with this file but it only loads the keyboard and console mod https://github.com/ZaneYork/SMAPI-Android-Installer/files/11144397/com.zane.stardewvalley.zip

**Comment by Dani141990** [comment]
That error went away for me after I deleted the config.user.json. I was suggested to months ago. So now I try this first when the error comes up after updates.

**Comment by EiKQr** [comment]
I just made it work I don't even know what I just did but it worked, before this I deleted and reinstalled from 0 at least 8 times everything right now I tried again and strangely it worked lmao I don't know what's wrong but thx

**Comment by ANKIT-PIXEL-413** [comment]
So what is the solution 🤔
