### ISSUE TITLE
Galaxy Store StardewValley

### ISSUE THREAD

**Issue by wally232** [ZaneYork/SMAPI-Android-Installer#5]
https://github.com/ZaneYork/SMAPI-Android-Installer/releases/tag/1.3.6

Galaxy Store StardewValley
SMAPI Installation still does not work.

Files Sent by Mail yesterday
Iinstalled the Stardew Valley_1.4.5.144.samsung.apk
Install the SMAPI.

The following installation errors occur

The game version is not supported.
Update the version or download a compatible package.

**Comment by ZaneYork** [comment]
switch to download menu choose and download the campat package for it



---Original---

**Comment by wally232** [comment]
switch to download menu choose and download the campat package for it 

I don't know exactly what you mean.

There are no selections in the Download menu.
Where can I find a compat package?

**Comment by ZaneYork** [comment]
---Original---

**Comment by wally232** [comment]
> 다운로드 메뉴로 전환 선택하고 campat 패키지를 다운로드하십시오.
> […](#)
> ---Original--- From: "wally232"<notifications@github.com&gt; Date: Tue, Mar 24, 2020 13:03 PM To: "ZaneYork/SMAPI-Android-Installer"<SMAPI-Android-Installer@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [ZaneYork/SMAPI-Android-Installer] Galaxy Store StardewValley (#5) https://github.com/ZaneYork/SMAPI-Android-Installer/releases/tag/1.3.6 Galaxy Store StardewValley SMAPI Installation still does not work. After I installed the StarDue Valley_1.4.5.144... Install the SMAPI. The following installation errors occur The game version is not supported. Update the version or download a compatible package. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
