### ISSUE TITLE
SVE, not compatible (?) 

### ISSUE THREAD

**Issue by xdlistic** [ZaneYork/SMAPI-Android-Installer#517]
Okay, so like, I downloaded the latest SVE mod and it's dependencies on my android phone and all the mods are working except for this. (see image below)

I clearly downloaded the latest version...

Do you guys have any idea on why this is happening to me?
![Screenshot_20230726-110438](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/122846635/e95e65d4-15c3-4937-a130-c669820e5d61)

**Comment by Zencee** [comment]
expanded is only coded for pc right now, unless the mod author makes it compatible to mobile you won't be able to run it without errors in game

**Comment by esih351h** [comment]
You can try either v 1.11.6 or 1.13.11 even with not compatible message it's seem running fine if u keep mods minimal and some crash on custom map if u really want to play sve

**Comment by xdlistic** [comment]
Someone just made a patch in the stardew valley expanded discord and now it's working properly. still not the official release though, but hey! if it works, it works.

**Comment by kwiknik78** [comment]
Can you post a link please?

**Comment by ImOnlyHuman1** [comment]
Hey xdlistic! How'd you manage to make sve work on android?  I've been having the same issues saying i need an updated version of the mod...

**Comment by kwiknik78** [comment]
Look in your stardew valley folder for this file.  Should be Android>data>com.zane.stardewvalley>files>smapi-internal>metadata.json
Look for "Stardew Valley Expanded": and change its status to "Assumecompatible".  This won't fix it, just allow it to run with some errors.  If it isn't there you can just add it like so:
  "Stardew Valley Expanded": {
            "ID": "FlashShifter.SVECode",
            "~1.14.24 | Status": "AssumeCompatible",
            "~1.14.24 | StatusReasonDetails": "fails to load due to an outdated implementation of the game's 'ICue' interface"
        }
