### ISSUE TITLE
Issues with loading the mods

### ISSUE THREAD

**Issue by Nxghtimesky** [ZaneYork/SMAPI-Android-Installer#518]
Ok so first smapi was having issues with loading the mods, so if i have mods already and added more it wouldnt load or even mention the new mods i added, so i reinstalled smapi to see if that'd fix it but it created an even bigger problem of not loading even the virtual keyboard. But now after reinstall a few more times, im having the same issue as before. here is a mod i added to test if its fixed or now, but still nope.
![Screenshot_20230726_194942](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/140627203/c5c628c5-e885-491b-b980-f3933e6ae12f)
![Screenshot_20230726_194954](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/140627203/4ca7f606-679e-4a74-9ca9-06e4532fe930)
![Screenshot_20230726_195012_ZArchiver](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/140627203/f28c84b5-3703-48b1-a67a-b3b6b1c6394b)

**Comment by Zencee** [comment]
Hi, all your mods must be placed in Android/data/com.zane.stardewvalley/files/Mods in order for them to be loaded in the game.

**Comment by Nxghtimesky** [comment]
> Hi, all your mods must be placed in Android/data/com.zane.stardewvalley/files/Mods in order for them to be loaded in the game.

**Comment by Nxghtimesky** [comment]
Hi yes thank you for that, but im actually having a new issue. I truly dont know what it is, but it just says error then i guess code? 

![Uploading Screenshot_20230729_180653.jpg…]()

**Comment by Nxghtimesky** [comment]
Yes, thank you for that, but now im facing a new issue, I dont fully know what it is but, when i open smapi, i get this error.

![Screenshot_20230729_180653](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/140627203/a6e16ce4-6936-4265-b5b1-6c4b8f77c05d)

And there is more text in that part.
