### ISSUE TITLE
Error with Newtonsoft

### ISSUE THREAD

**Issue by Azael7** [ZaneYork/SMAPI-Android-Installer#519]
When I open SMAPI, I get the same error as mentioned in #498. However I cannot understand what the other people who had the issue did to fix it. Can someone help explain how to fix it to me?

**Comment by Zencee** [comment]
if you are still having this issue you can just download a new com.zane from data folder to delete and replace yours. Your problem mostlikely comes from smapi-internal files inside your com.zane folder.

**Comment by I3elphegor** [comment]
Go to Android/data/com.zane.stardewvalley/files/smapi-internal and delete config.user.json. Looks like it is for smapi installer, but everytime you install smapi SV, it is copied to that folder and smapi SV tried to read it and crash.

**Comment by Azael7** [comment]
Got it, thanks!
