### ISSUE TITLE
How to install the error handler ?

### ISSUE THREAD

**Issue by Caeljin** [ZaneYork/SMAPI-Android-Installer#520]
What i need to do to install this error handler mod ? 
Any manual download since there is not an option using the smapi installer ?
![20230726_184545](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/128390700/c2a594b9-5af6-49e1-a6bb-c7b8be49f68c)

**Comment by Zencee** [comment]
afaik zane's android smapi doesn't have an error handler. If there are it should have been created together with virtual keyboard and console commands..

**Comment by esih351h** [comment]
Or if you have smapi on pc you can try to copy it to your phone

**Comment by Shockah** [comment]
Error Handler is not available for Android, because it’s not working as-is. Copying the PC version won’t do any good.

**Comment by Caeljin** [comment]
Ty

**Comment by Caeljin** [comment]
Solved
