### ISSUE TITLE
sve save game won't load or crash sometimes

### ISSUE THREAD

**Issue by vidhitchauhann** [ZaneYork/SMAPI-Android-Installer#53]
everything seems to perfect in the logs and not even using any heavy visual mods just cjb item and cheat menu with sve 1.11, but after clicking on my save file it won't load and the music keep Playing and suddenly get crashed after 2-3min. I thought maybe my save was corrupted, but the same thing happened with the new save file. I'm on android 10  custom rom. pls help

**Comment by vidhitchauhann** [comment]
let me know if you find the solution bunny bro

**Comment by BunnyX53** [comment]
![Screenshot_20201028-134123_SMAPI Installer](https://user-images.githubusercontent.com/66489338/97443784-54ab6300-1923-11eb-8659-b8d4b00eb7e6.jpg)
