### ISSUE TITLE
Can't locate StardewValley folder 

### ISSUE THREAD

**Issue by mwamon** [ZaneYork/SMAPI-Android-Installer#531]
I managed to install the SMAPI Installer and get SMAPI SDV. I used a File Explorer app to acess the Data folder since I have Android 13.

I ran into an issue of getting a constant loop of SMAPI Stardew Valley asking me to locate the contents of the StardewValley folder even after giving permission over and over again.

I cant use any other file app inside of SMAPI SDV to access the Data folder, so what now?

**Comment by kwiknik78** [comment]
I used cx file explorer to move all the mods.  It seems to be the best.  I also had an issue with the galaxy store version not being found so I got the play store version and it works.

**Comment by Zencee** [comment]
> I managed to install the SMAPI Installer and get SMAPI SDV. I used a File Explorer app to acess the Data folder since I have Android 13.
> 
> I ran into an issue of getting a constant loop of SMAPI Stardew Valley asking me to locate the contents of the StardewValley folder even after giving permission over and over again.
> 
> I cant use any other file app inside of SMAPI SDV to access the Data folder, so what now?

so have you fixed this issue?

**Comment by mwamon** [comment]
> > I managed to install the SMAPI Installer and get SMAPI SDV. I used a File Explorer app to acess the Data folder since I have Android 13.
> > I ran into an issue of getting a constant loop of SMAPI Stardew Valley asking me to locate the contents of the StardewValley folder even after giving permission over and over again.
> > I cant use any other file app inside of SMAPI SDV to access the Data folder, so what now?
> 
> so have you fixed this issue? if not, the simple way is to delete your "Stardew Valley" Folder as well as your "Smapi Stardew Valley" app and reinstall again your smapi sdv. This time when you open the app for the first time, allow access to you "Stardew Valley" folder it may ask twice and afterwards it should give you a message that it was a success and wants you to restart the app. ![IMG_20230804_145859](https://user-images.githubusercontent.com/129819788/258332461-4d8b78d3-00c9-4b34-a59f-5defb120cd77.jpg)

Ive since managed to get it installed! Just testing some mods, although DaisyNiko's Earthy recolor mod isnt working. It doesnt show in game.
