### ISSUE TITLE
Smapi loading issue

### ISSUE THREAD

**Issue by Mariiah-cog** [ZaneYork/SMAPI-Android-Installer#535]
Hey, so I've been trying to get back to playing stardew valley and I want to start over and I've tried alot of different smapi installers and the majority of them don't work but I've been trying everything to resolve the issue and now I'm just stuck
![Screenshot_20230807-012715](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/141612374/06593699-82f0-4a9d-99bb-0566e4a65605)
![Screenshot_20230807-012730](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/141612374/c9308515-bb2d-407b-9332-4dc4960fced0)
That's what I'm dealing with and I don't know how to resolve the issue because every time I click ok it takes me to my files app and when I click on stardew valley it does nothing, and I mean literally nothing because I'm pressing on the file and it won't click on it, I'm sorry to be an inconvenience but I just really want to play the game

**Comment by Zencee** [comment]
Hi, the quick fix is to just delete your "Stardew Valley" folder and" Smapi Stardew valley" app and reinstall normally afterwards.

**Comment by Mariiah-cog** [comment]
Okay thank you so much, I'll see if it works

**Comment by Mariiah-cog** [comment]
Hey so I tired but it still says the same thing or maybe I did something
wrong, I was wondering if you had a discord server I could join and I could
share my screen with you and you help me or that's too personal, also, the
stardew that I have, I downloaded it for free from a site

**Comment by Zencee** [comment]
oh yeah we have a discord but i don't think I can share it here idk. You can chat me if you still need help discord: ceezen

**Comment by Mariiah-cog** [comment]
Okay, thank you!

**Comment by Mariiah-cog** [comment]
I sent a friend request

**Comment by kwiknik78** [comment]
I couldn't use the galaxy store version but the play store version was recognized without a hitch.  Which version do you have?

**Comment by Zencee** [comment]
Please close this thread since its already been fixed.

**Comment by Mariiah-cog** [comment]
Thank you
