### ISSUE TITLE
Mods i have added to my mods folder dont show up in smapi

### ISSUE THREAD

**Issue by Mariiah-cog** [ZaneYork/SMAPI-Android-Installer#540]
Hey, I was wondering what I should do if some mods don't load even though I added them to the mods folder
![Screenshot_20230808-130832](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/141612374/e4c2029c-77fa-4f05-a9af-4fcfb1e4de92)
And it says that those 3 mods don't work, at first I had them but I deleted them when I saw they weren't working but it still has them there and new mods that I want to check out don't show up as mods that I've added
![Screenshot_20230810-125114](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/141612374/d2acdac1-25d9-459b-90fa-ca539990055e)
These are the mods I have and majority of them don't show up in the game, only 4 of those mods actually show up in the game
![Screenshot_20230810-125254](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/141612374/0f1b1e2d-5855-4465-a7ef-a9c4f189a815)
Those are the mods that show up in the game

**Comment by RakanIV** [comment]
Update your content patcher. You're using the old one
Not sure about the look up anything tho.

**Comment by RakanIV** [comment]
I think look up anything doesn't work for smapi mobile
