### ISSUE TITLE
Delete old mod feature

### ISSUE THREAD

**Issue by ellipszist** [ZaneYork/SMAPI-Android-Installer#55]
I need delete my old bundled mods in `StardewValley\Mods` folder, Before install new bundled mods on phone smapi installed app. (update app new version on playstore). can you make it this feature?

**Comment by ZaneYork** [comment]
Okay, I'll add a new feature to deal with this request. How about add a new manifest config key like `clean install = true` ?

**Comment by ellipszist** [comment]
`clean install = true` i like it.

**Comment by ellipszist** [comment]
new manifest config key delete mods in list by array like `Console Commands, CustomLocalization, SaveBackup, VirtualKeyboard`?

**Comment by ZaneYork** [comment]
![image](https://user-images.githubusercontent.com/17948308/96573203-6035d300-1300-11eb-9a3c-e109f1d96498.png)
Like this, if set to true, it will delete the old mod before install the new version

**Comment by ellipszist** [comment]
My mod is `AndroidModTH ` in `StardewValley\Mods`
` 
{
    "assetPath":"mods/android-modth.zip",
    "Name": "AndroidModTH",
    "UniqueID": "AndroidModTH"
  },
`
But i need rename my mod to `[CP] ModTH`, My new code is?

**Comment by ZaneYork** [comment]
Did you changed your mod's UniqueId?

**Comment by ellipszist** [comment]
> Did you changed your mod's UniqueId?

yes.

**Comment by ellipszist** [comment]
example: Update `SVE 1.10` to SVE `1.11`

**Comment by ZaneYork** [comment]
![image](https://user-images.githubusercontent.com/17948308/96574410-fe766880-1301-11eb-8e91-0ceb403b5e7a.png)

Okay, like this

**Comment by ellipszist** [comment]
example:

delete SVE 1.10 (old version)
- Mods\(Stardew Valley Expanded)
- Mods\[CM] Stardew Valley Expanded
- Mods\[FTM] Stardew Valley Expanded
- Mods\[JA] Stardew Valley Expanded
- Mods\[TMX] Stardew Valley Expanded
- Mods\StardewValleyExpanded

install SVE 1.11 (new version)
+ Mods\Stardew Valley Expanded\[CM] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[CP] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[FTM] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[JA] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[TMX] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\StardewValleyExpanded

`-` delete old mods, `+` install new mods

**Comment by ZaneYork** [comment]
if new mod has the same unique id, it will overwrite automaticlly to the origin path, if you wants to reset it, simply set CleanInstall to true

**Comment by ellipszist** [comment]
Mod Pack is work? `manifest.json` in mod sub folder is many unique id. e.g. SVE 1.11

```
+ Mods\Stardew Valley Expanded\[CM] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[CP] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[FTM] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[JA] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\[TMX] Stardew Valley Expanded
+ Mods\Stardew Valley Expanded\StardewValleyExpanded
```

**Comment by ZaneYork** [comment]
Already support this feature in 1.7.0 version, with minor adjust.
1. Outdated mod in `OriginUniqueId` list will be clean up when `CleanInstall` set to true.
2. Outdated mod with same `UniqueID` and the installed version is below `Version` of manifest will be clean up when `CleanInstall` set to true.

**Comment by ellipszist** [comment]
before CleanInstall
```
-  \Mods\AndroidModTH
  - assets
  - config.json
  - content.json
  - How To Config Fonts.png
  - manifest.json <- v1.8.9-beta14
```

New code.
  {
    "assetPath":"mods/android-modth.zip",
    "Name": "Stardew Valley Thai Language (Mobile)",
    "UniqueID": "TranslatorArmy.ModTH",
    "CleanInstall": true,
    "Version": "1.8.9-beta14",
    "OriginUniqueId": ["TranslatorArmy.ModTH"]
  },

manifest.json is work, but has sub folder.
```
-  \Mods\AndroidModTH
  - AndroidModTH\assets <- has sub folder
  - AndroidModTH\config.json <- has sub folder
  - AndroidModTH\content.json <- has sub folder
  - AndroidModTH\How To Config Fonts.png <- has sub folder
  - AndroidModTH\manifest.json <- v1.9.0 & has sub folder
```

**Comment by ZaneYork** [comment]
Could you please provide the difference of mod file structure more clearly?

**Comment by ellipszist** [comment]
after click "INSTALL" button smapi create mod in mod (sub folder) e.g. StardewValley\Mods\AndroidModTH\**AndroidModTH**

**Comment by ZaneYork** [comment]
> after click "INSTALL" button smapi create mod in mod (sub folder) e.g. StardewValley\Mods\AndroidModTH\AndroidModTH

You may needs to check the file structure of android-modth.zip

**Comment by ZaneYork** [comment]
> after click "INSTALL" button smapi create mod in mod (sub folder) e.g. StardewValley\Mods\AndroidModTH\AndroidModTH

The name of the manifest should be equals to the sub directory of the mod's zip entry, the upgrade stage will try to remove the prefix of manifest's name section to make sure no sub directory will be created
![image](https://user-images.githubusercontent.com/17948308/97137123-0d409d80-1790-11eb-9960-ee1a05410bf9.png)

**Comment by ellipszist** [comment]
Click "INSTALL" (1st time)
```
-  \Mods
  - AndroidModTH
  - Console Commands
  - ContentPatcher
  - CustomLocalization
  - SaveBackup
  - VirtualKeyboard
```
Click "INSTALL" again (2nd time)
```
-  \Mods
  - AndroidModTH\AndroidModTH
  - Console Commands
  - ContentPatcher\ContentPatcher
  - CustomLocalization
  - SaveBackup
  - VirtualKeyboard\VirtualKeyboard
```

**Comment by ZaneYork** [comment]
Every thing will OK if you make your manifest's Name section from `Stardew Valley Thai Language (Mobile)` to `AndroidModTH`

**Comment by ellipszist** [comment]
Thanks.

Can i rename?
`"Name": "648c4b387c5b61642614aa6677909a755a9b84fd96d717703fc83f5f73f515c0board",`
to
`"Name": "VirtualKeyboard",`

**Comment by ellipszist** [comment]
> Every thing will OK if you make your manifest's Name section from `Stardew Valley Thai Language (Mobile)` to `AndroidModTH`

Thanks.

I can change the name?
"Name": "648c4b387c5b61642614aa6677909a755a9b84fd96d717703fc83f5f73f515c0board",
to
"Name": "VirtualKeyboard",

**Comment by ZaneYork** [comment]
The name of mod's manifest in `mods_manifest.json` file should be equals to the entry name of the zip file's root, or else it will create a sub folder to the mod's assert path when upgrade.
This name does not needs to equal with the name of mod's Name section in `manifest.json` of their own,

**Comment by ZaneYork** [comment]
> > Every thing will OK if you make your manifest's Name section from `Stardew Valley Thai Language (Mobile)` to `AndroidModTH`
> 
> Thanks.
> 
> I can change the name?
> `"Name": "648c4b387c5b61642614aa6677909a755a9b84fd96d717703fc83f5f73f515c0board",`
> to
> `"Name": "VirtualKeyboard",`

When was it changed to 648c4b387c5b61642614aa6677909a755a9b84fd96d717703fc83f5f73f515c0board? It is a wrong config, I'll fix it on next release
