### ISSUE TITLE
Mod compatibility 

### ISSUE THREAD

**Issue by Azael7** [ZaneYork/SMAPI-Android-Installer#551]
I was just wondering if there was a site to check for mobile mod compatibility with the current SMAPI build? When I use SMAPI.io/mods Most of what it tells me is compatible is no (eg. Deepwoods) and I don't know if it is a user or a site error

**Comment by TeamDeity** [comment]
> I was just wondering if there was a site to check for mobile mod compatibility with the current SMAPI build? When I use SMAPI.io/mods Most of what it tells me is compatible is no (eg. Deepwoods) and I don't know if it is a user or a site error

I'm not too sure either. Some people on YouTube link mods for mobile that are working for SDV 1.5.6 though. You'll have to look them up. That's where I was able to use mods that worked.

**Comment by Kitty035** [comment]
No there is nowhere to check for that.
