### ISSUE TITLE
What Mod Causing To Crashes

### ISSUE THREAD

**Issue by ssaagamemer** [ZaneYork/SMAPI-Android-Installer#554]
so here is lastest logs

**Comment by ssaagamemer** [comment]
https://pastebin.com/FJUN1gLN

i cant import an log txt to here

**Comment by Haerinah** [comment]
check your sve folder cause smapi says its empty also you need to download the patch file for sve on their discord for sve to work. Almanac also crashes your game

**Comment by ssaagamemer** [comment]
oh i tried and it work normally now
