### ISSUE TITLE
Google Play doesn't support MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by ellipszist** [ZaneYork/SMAPI-Android-Installer#56]
Your APK or Android App Bundle requests the 'android.permission.MANAGE_EXTERNAL_STORAGE' permission, which Google Play doesn't support yet.

**Comment by ZaneYork** [comment]
This permission is requested for device of Android R, you may needs to remove it in order to upload to Google Play. I won't remove it, or else the Android R device cant works properly

**Comment by ellipszist** [comment]
Please pull requests code to me.
https://github.com/ellipszist/SMAPI-Android-Installer/pulls

**Comment by ZaneYork** [comment]
> Please pull requests code to me.
> https://github.com/ellipszist/SMAPI-Android-Installer/pulls

Simply modify the AndroidManifest.xml and remove this permission request, only affect the Android R

**Comment by ellipszist** [comment]
> > Please pull requests code to me.
> > https://github.com/ellipszist/SMAPI-Android-Installer/pulls
> 
> Simply modify the AndroidManifest.xml and remove this permission request, only affect the Android R

Thank you..
