### ISSUE TITLE
Help! Black screen when go to sleep.

### ISSUE THREAD

**Issue by lalala20120** [ZaneYork/SMAPI-Android-Installer#561]
It like 5th day of my new farm and I'm not using any mod (except 2 default "ConsoleCommand" and "Virtualkeyboard").Maybe something wrong with my game?
https://smapi.io/log/2d4f876b5aaa4a4a9ddfc0cbc45c67a1

**Comment by Haerinah** [comment]
what mods do you use before this happened?

**Comment by lalala20120** [comment]
Oh sorry for slow respond, I already created new farm again and doing great.
> what mods do you use before this happened?

I installed SVE earlier which crash my game then I have to delete it but I forgot to delete SVE required mod so my old save is corrupted.
