### ISSUE TITLE
Smapi crashing when loading save 

### ISSUE THREAD

**Issue by Himecold** [ZaneYork/SMAPI-Android-Installer#569]
I use smapi 3.18.3.3 and stardew valley 1.5.6.39
After creating a save and play it the first time, the second time I load it, the game will show the loading screen and then crash. I have 153 mods and none of them show any error in the log. In a desperate attempt, I even try to delete some mods that might be the problem but to no avail. Can anyone help me with this problem?

**Comment by Zencee** [comment]
are you using sve? since sve is still on beta it isn't recommended to use a lot of mods with it.

**Comment by Himecold** [comment]
No, I don't use it, I don't use mod that isn't an official version,

**Comment by Himecold** [comment]
So sorry, I'm new to github and haven't really used to it yet

**Comment by Zencee** [comment]
alright do you atleast have a crash log? it should be created inside your errorlogs folder if your game crashes.

**Comment by Himecold** [comment]
Hello, after looking at the error log, I try to move all the mods into a different folder and the game seems to be working fine. It seems to be that the game or my phone cannot handle the amount of mods I put into it, I'll try to erase the mod bit by bit until it works, thank you so much for your help, I appreciate it, thank you.
