### ISSUE TITLE
Game wont load

### ISSUE THREAD

**Issue by BunnyX53** [ZaneYork/SMAPI-Android-Installer#57]
Updated Stardew Valley on Playstore. Since then the game won't even open

**Comment by BunnyX53** [comment]
![Screenshot_20201028-134123_SMAPI Installer](https://user-images.githubusercontent.com/66489338/97443859-6b51ba00-1923-11eb-8c76-8933b69e2901.jpg)

**Comment by ellipszist** [comment]
Same issue (Samsung Galaxy Note 20 Ultra) just happen today.
2 days ago I installed this lastest version 1.7.0 on Oct 26  everything goes fine.
but today I reinstalled it by push on Install button then the errors happen

try on uninstall all SMAPI and Stardew game not working
factory reset the phone and reinstall game and SMAPI it still not working

here is Debugged mode log

ADB
```

10/28 21:10:02: Launching 'app' on samsung SM-N985F.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.ell.smapiinstaller/com.zane.smapiinstaller.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 19141 on device 'samsung-sm_n985f-R58N805NHVV'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/PhoneWindow: forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474 
I/MultiWindowDecorSupport: [INFO] isPopOver = false
    updateCaptionType >> DecorView@3a42e61[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@3a42e61[]
W/.smapiinstalle: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/ConnectivityManager: requestNetwork; CallingUid : 10273, CallingPid : 19141
I/ViewRootImpl@bab5539[MainActivity]: setView = com.android.internal.policy.DecorView@3a42e61 TM=true MM=false
I/ViewRootImpl@bab5539[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)0 dur=4 res=0x7 s={true 542505738240} ch=true
D/OpenGLRenderer: createReliableSurface : 0x7db71e41c0(0x7e4fdca000)
D/OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x0
I/mali_winsys: new_window_surface() [1080x2316] return: 0x3000
D/OpenGLRenderer: eglCreateWindowSurface : 0x7db71d0700
D/OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x7db71d0700
W/Gralloc3: mapper 3.x is not supported
I/gralloc: Arm Module v1.0
I/ViewRootImpl@bab5539[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)0 dur=5 res=0x1 s={true 542505738240} ch=false
I/ViewRootImpl@bab5539[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3a42e61[MainActivity]
    getNavigationBarColor() -855310
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3a42e61[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.ell.smapiinstaller ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
I/ViewRootImpl@bab5539[MainActivity]: MSG_RESIZED: frame=(0,0,1080,2316) ci=(0,67,0,126) vi=(0,67,0,126) or=1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3a42e61[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.ell.smapiinstaller ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/libmdf: libmdf v2.9.0.0 On 64bit PLATFORM
I/ViewRootImpl@bab5539[MainActivity]: ViewPostIme pointer 0
I/ViewRootImpl@bab5539[MainActivity]: ViewPostIme pointer 1
I/ViewRootImpl@bab5539[MainActivity]: ViewPostIme pointer 0
I/ViewRootImpl@bab5539[MainActivity]: ViewPostIme pointer 1
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
I/ViewRootImpl@bab5539[MainActivity]: MSG_RESIZED: frame=(0,0,1080,2316) ci=(0,67,0,126) vi=(0,67,0,126) or=2
D/OpenGLRenderer: makeCurrent EglSurface : 0x7db71d0700 -> 0x0
    destroyEglSurface : 0x7db71d0700
I/mali_egl: eglDestroySurface() in
I/mali_winsys: delete_surface() [1080x2316] return
I/mali_egl: eglDestroySurface() out
E/OpenGLRenderer: ReliableSurface: perform returned an error
W/libEGL: EGLNativeWindowType 0x7db71e41d0 disconnect failed
D/OpenGLRenderer: ~ReliableSurface : 0x7db71e41c0
    endAllActiveAnimators on 0x7dba5c3600 (RippleDrawable) with handle 0x7dbe74dc20
I/ViewRootImpl@bab5539[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)8 dur=11 res=0x5 s={false 0} ch=true
I/ViewRootImpl@bab5539[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@3a42e61[MainActivity]
    getNavigationBarColor() -855310
I/ViewRootImpl@bab5539[MainActivity]: stopped(true) old=false
I/ViewRootImpl@bab5539[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(67,0,2316,1080) req=(1080,2316)4 dur=3 res=0x1 s={false 0} ch=false
I/ViewRootImpl@bab5539[MainActivity]: dispatchDetachedFromWindow
D/InputTransport: Input channel destroyed: '3a96159', fd=71
D/PhoneWindow: forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474 
I/MultiWindowDecorSupport: [INFO] isPopOver = false
    updateCaptionType >> DecorView@dbd5f4e[], isFloating: false, isApplication: true, hasWindowDecorCaption: false, hasWindowControllerCallback: true
D/MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@dbd5f4e[]
W/AppCenter: App Center may only be configured once.
I/ViewRootImpl@af97e3b[MainActivity]: setView = com.android.internal.policy.DecorView@dbd5f4e TM=true MM=false
I/ViewRootImpl@af97e3b[MainActivity]: Relayout returned: old=(0,0,2316,1080) new=(67,0,2316,1080) req=(2316,1080)0 dur=4 res=0x7 s={true 537962315776} ch=true
D/OpenGLRenderer: createReliableSurface : 0x7db71e41c0(0x7d410d8000)
I/mali_winsys: new_window_surface() [2249x1080] return: 0x3000
D/OpenGLRenderer: eglCreateWindowSurface : 0x7d58fe6500
D/OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x7d58fe6500
I/ViewRootImpl@af97e3b[MainActivity]: Relayout returned: old=(67,0,2316,1080) new=(67,0,2316,1080) req=(2249,1080)0 dur=9 res=0x1 s={true 537962315776} ch=false
V/ViewRootImpl@af97e3b[MainActivity]: updateAppliedLetterboxDirection, direction=1, Caller=android.view.ViewRootImpl.handleDispatchLetterboxDirectionChanged:8043
I/ViewRootImpl@af97e3b[MainActivity]: MSG_RESIZED: frame=(67,0,2316,1080) ci=(0,63,126,0) vi=(0,63,126,0) or=2
D/DecorView: semSetRoundedCorners: 5
I/ViewRootImpl@af97e3b[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@dbd5f4e[MainActivity]
    getNavigationBarColor() -855310
D/InputMethodManager: prepareNavigationBarInfo() DecorView@dbd5f4e[MainActivity]
    getNavigationBarColor() -855310
V/InputMethodManager: Starting input: tba=com.ell.smapiinstaller ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel destroyed: 'ClientS', fd=81
```

**Comment by vidhitchauhann** [comment]
latest version means 1.4.5.147? I updated it yesterday but the game runs well with smapi but keep having the old crashes I was facing

**Comment by BunnyX53** [comment]
My version is 1.4.5.138

**Comment by Jonqora** [comment]
.138 probably isn't your version, that's the minimum required by android smapi.

If you look at app information, you can find out. Mine is 1.4.5.145, yours should be later than that.

For me, I get there by opening the list of apps, then tapping and dragging the Stardew Valley app icon to "App Information" at the top.

**Comment by BunnyX53** [comment]
Ahh my mistake. Mines 1.4.5.148 apparently

**Comment by ZaneYork** [comment]
> Ahh my mistake. Mines 1.4.5.148 apparently

I have not get this update, I'll test the compatibility issue after I got this 1.4.5.148 version of the game

**Comment by SabiMiyato** [comment]
Thank you, sir@Jonqora  @ZaneYork  confirmed that's pronblem with game version 1.4.5.148

From 'Ell Commented ; because yesterday, I'm updated the game and so my current game version is 1.4.5.148 and my smapi stop working, so, when I try as both of you said - I use an akp game version 1.4.5.145 instead and now it's working!  🙏🙏

 thank you so much

![Screenshot_20201029-101153_Google Play Store](https://user-images.githubusercontent.com/62402134/97523224-42d5c880-19d4-11eb-9b01-e4d8f5cc7ce3.jpg)

**Comment by BunnyX53** [comment]
Any news on this? As I still can't play the game

**Comment by ZaneYork** [comment]
> Any news on this? As I still can't play the game

Already decrypt the updated game's assemblies, but it has upgrade to Mono Android 10 platform, so I need to make more work to deal with it, may takes several weeks. So, do not upgrade to 1.4.5.148 if possible.

**Comment by BunnyX53** [comment]
Thanks for reply. Not much I can do about  update since I have done it and thats why I have the problem lol

**Comment by vidhitchauhann** [comment]
Bunny I'd recommend you to downgrade your game :3 install 1.4.5.1.4.5version

**Comment by BunnyX53** [comment]
> Bunny I'd recommend you to downgrade your game :3 install 1.4.5.1.4.5version

How?

**Comment by vidhitchauhann** [comment]
like downloading an apk file from google

**Comment by Eliza-cell** [comment]
Meu smapi também não abre mais, e não carrega o jogo, por favor ajude eu amo este jogo e jogo todos os dias.

**Comment by BunnyX53** [comment]
Any updates? I'm stil not able to play

**Comment by ZaneYork** [comment]
> Any updates? I'm stil not able to play

It still keeps crashing on my device too :(
I'll try my best to deal with it. The game was encrypted and the SDK was minified, so I needs to make lots of tweaks in this situation.

**Comment by LuxiMalikSuzumori** [comment]
Mine won't even open. Is there any progress being made so far to fix it?

**Comment by LuxiMalikSuzumori** [comment]
I hope it's resolved soon... modded Stardew is one of the only joys in my life xD

**Comment by LuxiMalikSuzumori** [comment]
Any updates??

**Comment by LuxiMalikSuzumori** [comment]
still cant play

**Comment by LuxiMalikSuzumori** [comment]
is there any updates with fixing this? game still wont load

**Comment by vidhitchauhann** [comment]
to anyone looking for a fix, you can download the apk version of the from from third party sources like google, Look for version 1.4.5.147 install that apk and your game will run then.

**Comment by LuxiMalikSuzumori** [comment]
@vidhitchauhann sometimes apk doesnt work. thats why im still waiting for the update fix

**Comment by vidhitchauhann** [comment]
delete your current apk, and download the apk and data file frome this site, https://rexdlfile.com/index.php?id=stardew-valley-apk
(download the normal apk with data, download download tha mod one)
install the apk and then place the data game folder to obb, after that open your smapi and click on install, wait for a while after that run that smapi stardew valley and enjoy the game. it will work 100%

**Comment by BunnyX53** [comment]
That didn't work

**Comment by vidhitchauhann** [comment]
what issue you're facing?

**Comment by BunnyX53** [comment]
Got it. Had to delete smapi stardewvalley too

**Comment by vidhitchauhann** [comment]
contact me on telegram I'll help, here's my link
https://t.me/Hakaishino

**Comment by vidhitchauhann** [comment]
ohh so it worked right? pls confirm it

**Comment by BunnyX53** [comment]
I tried a different site for the apk and its worked

**Comment by LuxiMalikSuzumori** [comment]
@vidhitchauhann im not using an apk. they dont work for me. please dont force it. id rather wait for the regular smapi to work. hence why i have been asking if there has been any updates with fixing it.

**Comment by vidhitchauhann** [comment]
I'm sorry, it is just that you've been asking for a fix but i don't even know myself when it will come. :c

**Comment by LuxiMalikSuzumori** [comment]
nono its ok. Im just not a patient person xD Sorry for that

**Comment by vidhitchauhann** [comment]
haha I'll still suggest you to try apk if it doesn't work you can search for it on YouTube :c So that you can finally play the modded stardew valley.  :c

**Comment by LuxiMalikSuzumori** [comment]
ill try an apk again and see how it goes. thank you for your suggestion and i apologize if i was rude :c

**Comment by vidhitchauhann** [comment]
make sure to delete all apk, like the base game and modded version that is crashing. you were not being rude, you just wanted to play the game, I can understand. :c

**Comment by LuxiMalikSuzumori** [comment]
will do! :)

**Comment by LuxiMalikSuzumori** [comment]
it worked! now i can play :D

**Comment by vidhitchauhann** [comment]
I'm glad :c

**Comment by LuxiMalikSuzumori** [comment]
@ZaneYork is there any update on the fix though?

**Comment by LuxiMalikSuzumori** [comment]
Ok so its been 3 weeks with no update. can someone PLEASE tell me if theres a fix???

**Comment by BunnyX53** [comment]
> Ok so its been 3 weeks with no update. can someone PLEASE tell me if theres a fix???

They're busy. They do this in their free time. Be patient

**Comment by LuxiMalikSuzumori** [comment]
> They're busy. They do this in their free time. Be patient

Im not trying to be impatient. I'm genuinely asking if there has been any progress or update to this solution. Im not pushing or forcing. I'm just asking becausebit has been a while.

**Comment by LuxiMalikSuzumori** [comment]
I get antsy if I can't figure things out or get info I'm looking for. Either my ADHD or OCD makes me like that

**Comment by BunnyX53** [comment]
I think its the three ??? That make you look impatient, just saying

**Comment by LuxiMalikSuzumori** [comment]
well im sorry but it wasnt my intention.

**Comment by LuxiMalikSuzumori** [comment]
> I think its the three ??? That make you look impatient, just saying. And you asked for a fix not an update

not trying to be rude but i have communication issues so you picking apart what im saying, was very hurtful. *just saying*

**Comment by vidhitchauhann** [comment]
zane hasn't been online since November, you can check un the contribution activity. He's basically offline or busy in his work. So i think he will fix this issue in next year.

**Comment by vidhitchauhann** [comment]
Once again I'll say this for people having issues just downgrade your game and enjoy with smapi, or you can wait whenever the update or fix comes. :c

**Comment by LuxiMalikSuzumori** [comment]
> zane hasn't been online since November, you can check un the contribution activity. He's basically offline or busy in his work. So i think he will fix this issue in next year.

Thank you. I was just talking to a member of the Stardew Discord server, and have also been in contact with Pathoschild about it so I am learning as I go and trying to be patient as best I can. I appreciate what they do, and I do not mean to sound impatient.

**Comment by LuxiMalikSuzumori** [comment]
I will keep using the apk until its fixed

**Comment by BunnyX53** [comment]
> > I think its the three ??? That make you look impatient, just saying. And you asked for a fix not an update
> 
> not trying to be rude but i have communication issues so you picking apart what im saying, was very hurtful. _just saying_

Your not the only one who has communication issues

**Comment by LilyJk8197** [comment]
hello!! I have problems opening smapi Android, since I installed it I have done the whole process and everything is fine but when I want to open the application it does not open

**Comment by LilyJk8197** [comment]
![Screenshot_2023-10-27-00-55-40-717_com miui bugreport](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/148944209/54524c9a-7ba8-4343-b13f-63c799f6fee3)

**Comment by LilyJk8197** [comment]
That only appears to me, I don't know what it means.
