### ISSUE TITLE
Can't install SMAPI

### ISSUE THREAD

**Issue by Miche916** [ZaneYork/SMAPI-Android-Installer#571]
![Screenshot_2023-09-19-04-49-39-42_289ce727d0c54b7a6b438eba754ebac7](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/145398374/651001a1-f18f-466b-8d76-7bbcad121a73)

This pops up everytime I press install

**Comment by Zencee** [comment]
delete "StardewValley" folder and try again

**Comment by Miche916** [comment]
> delete "StardewValley" folder and try again
