### ISSUE TITLE
Shipping bin not working 

### ISSUE THREAD

**Issue by MossyBone** [ZaneYork/SMAPI-Android-Installer#573]
So, vanilla version 2orks just fine, but when i run the game from smapi, I can't place anything into a shipping bin. Perhaps there is a mod that can interfere with that? but nothing comes to mind, I don't have much mods installed
Obviously, can't play the game if I can't sell anything, it's frustrating. The item just don't get into a shipping bin slot

**Comment by Zencee** [comment]
have you checked your log for any errors?

**Comment by MossyBone** [comment]
> have you checked your log for any errors?

you're a savior, i forgot that error logs existed. took me a minute to figure out how to use it, but yeah, it was error in the mod 'chests everywhere'. deleted it and it works fine now

Thank you!!
