### ISSUE TITLE
Issues installing SMAPI

### ISSUE THREAD

**Issue by TacitaNix** [ZaneYork/SMAPI-Android-Installer#595]
When I download the app and attempt to install it I get this error but I don't know what I did wrong or how to fix it?

![Screenshot_20231008_094050_Package installer](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/147326460/aecf26c7-0114-4f64-ab9f-734b810dbdd2)

**Comment by TacitaNix** [comment]
Update, I had an old version if SMAPI apparently and fixed that/got it to install but I have a new error that I don't know how to fix.

![Screenshot_20231008_102425](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/147326460/bee55dab-264b-420e-802a-9d222b1d507a)

**Comment by TacitaNix** [comment]
Figured it out looking through previous issues others had

**Comment by Nizarberyan** [comment]
> Figured it out looking through previous issues others had

Can you help me i have the same problem

**Comment by TacitaNix** [comment]
>> Can you help me i have the same problem

Ok so I had an old version of SMAPI to start so I would go to the following link to get the latest version.
https://github.com/ZaneYork/SMAPI-Android-Installer/releases

As for the second issue, before installing the apk I complwtely deleted the stardew valley folder in my files so everything was brand new and fresh and that seemed to work for me.
