### ISSUE TITLE
issue when launching smapi

### ISSUE THREAD

**Issue by Nizarberyan** [ZaneYork/SMAPI-Android-Installer#596]
Recently I had a problem with SMAPI it refused to install or when I went on GitHub to the issues
page I found a version on MediaFire when I downloaded it it worked but when I launched it with mods showed me this screen
![Screenshot_2023-10-09-19-39-54-539_com zane stardewvalley](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/147407729/5e833d84-8b4d-4ae7-ae20-1c3de5a62449)

**Comment by Zencee** [comment]
can you send your error log?

**Comment by Nizarberyan** [comment]
> can you send your error log?

I uploaded it on MideaFire [Here](https://www.mediafire.com/file/ewnl4xjzptuq3ve/SMAPI-log.zip/file)

**Comment by Nizarberyan** [comment]
> can you send your error log?

I sent you a friend request on discord

**Comment by Zencee** [comment]
your log states that your smapi-internal files were lacking some important files to it. That's why you're having those errors, I'll try and upload a fresh one here and try it if it works for you.

**Comment by Zencee** [comment]
https://www.mediafire.com/file/62roavxebkscfnq/StardewValley.zip/file

Delete your own "StardewValley" folder and replace it with this fresh copy. Delete also your "com.zane.stardewvalley" inside your android/data folder then afterwards run your smapi sdv, it will ask you again to locate your StardewValley folder twice. Just do as what is says and that should be it

**Comment by Nizarberyan** [comment]
> https://www.mediafire.com/file/62roavxebkscfnq/StardewValley.zip/file
> 
> Delete your own "StardewValley" folder and replace it with this fresh copy. Delete also your "com.zane.stardewvalley" inside your android/data folder then afterwards run your smapi sdv, it will ask you again to locate your StardewValley folder once or twice. Just do as what it says and after you get the message migration finished that should be it

Thanks it worked

**Comment by LeCromwell** [comment]
Dude, seriously thanks, it works perfectly.

**Comment by ainedroid** [comment]
ik this theead is from a year ago, and i've tried following all @Zencee 's step but i couldn't get my patched apk to work, it kept on showing this 
![Screenshot_20240927_160612](https://github.com/user-attachments/assets/057f0927-e11b-49f1-b936-1a21200956b2)

and this message whenever i try to fix the com. and StardewValley file
![279185700-fbf5cbbd-f533-4215-896c-19f60b087a84](https://github.com/user-attachments/assets/92b887f9-4085-415d-89a5-49bb8b2245a9)

i'm not sure on what to find or fix anymore tbh, nothing seemed to work

**Comment by Zencee** [comment]
> and this message whenever i try to fix the com. and StardewValley file ![279185700-fbf5cbbd-f533-4215-896c-19f60b087a84](https://private-user-images.githubusercontent.com/183070795/371468181-92b887f9-4085-415d-89a5-49bb8b2245a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Mjg3NDYsIm5iZiI6MTcyNzQyODQ0NiwicGF0aCI6Ii8xODMwNzA3OTUvMzcxNDY4MTgxLTkyYjg4N2Y5LTQwODUtNDE1ZC04OWE1LTQ5YmI4YjIyNDVhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwOTE0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzJlNWI1YjExYzhmOWI2Mzk1NDJjMDE0Yjg2YWQ5NDBhM2YxZTUyN2M0NzM4ZmM4MzI1M2VjZTA5M2IxNGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BUMcnd5Hnhd4iCuZAF0Be6xWHogNdaXp5weJ7ld_pe8)
> 
> i'm not sure on what to find or fix anymore tbh, nothing seemed to work

if you still have the "failed to initialize" error that pops up when starting then theres an already known quick fix for it, just go to your com.zaneyork 📁 and open smapi-installer and inside the folder delete the `config.user.json` file. You should be good after that

**Comment by ainedroid** [comment]
> > and this message whenever i try to fix the com. and StardewValley file ![279185700-fbf5cbbd-f533-4215-896c-19f60b087a84](https://private-user-images.githubusercontent.com/183070795/371468181-92b887f9-4085-415d-89a5-49bb8b2245a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0Mjg3NDYsIm5iZiI6MTcyNzQyODQ0NiwicGF0aCI6Ii8xODMwNzA3OTUvMzcxNDY4MTgxLTkyYjg4N2Y5LTQwODUtNDE1ZC04OWE1LTQ5YmI4YjIyNDVhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QwOTE0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzJlNWI1YjExYzhmOWI2Mzk1NDJjMDE0Yjg2YWQ5NDBhM2YxZTUyN2M0NzM4ZmM4MzI1M2VjZTA5M2IxNGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BUMcnd5Hnhd4iCuZAF0Be6xWHogNdaXp5weJ7ld_pe8)
> > i'm not sure on what to find or fix anymore tbh, nothing seemed to work
> 
> if you still have the "failed to initialize" error that pops up when starting then theres an already known quick fix for it, just go to your com.zane.stardew 📁 and open smapi-internal and inside the folder delete the `config.user.json` file. You should be good after that

okay, so this works! i got it to stop crashing, but now i'm stuck in a loop of confirming the content in the stardewvalley file. i've had it confirmed multiple times but when i restarted the game, it still told me to confirm the file contents.

**Comment by Amorphodrome** [comment]
Sorry for coming back to this but i've followed @Zencee 's step by steps about 5 times now and i still keep getting this error
![SMAPI Stardew Valley_2024-11-29-17-13-52](https://github.com/user-attachments/assets/0927fb6d-8b30-4eca-ba0c-2708cc793bd3)
I have deleted the files and downloaded them again but it still comes up like this
