### ISSUE TITLE
Infinite loading problem

### ISSUE THREAD

**Issue by TeamDeity** [ZaneYork/SMAPI-Android-Installer#598]
I downloaded all working versions for SDV 1.5.6 and have uninstalled both the original game and Smapi multiple times and redownloaded them. However, I don't have many mods on my phone and I use Blu F92e Android version 12. I go into the game, no red text whatsoever as I downloaded mods that worked on android and for the current version of SDV and all I get is an infinite loading screen with the music playing in the background. Will someone help me out?

**Comment by Zencee** [comment]
kindly send your recent log when you get stuck on the game so we could help you out more.

**Comment by TeamDeity** [comment]
> kindly send your recent log when you get stuck on the game so we could help you out more.

How exactly do I do that again?

**Comment by Zencee** [comment]
> > kindly send your recent log when you get stuck on the game so we could help you out more.
> 
> How exactly do I do that again?

send the txt file inside your com.zane.stardewvalley/files/ErrorLogs folder

**Comment by TeamDeity** [comment]
> > > kindly send your recent log when you get stuck on the game so we could help you out more.
> > 
> > 
> > How exactly do I do that again?
> 
> send the txt file inside your com.zane.stardewvalley/files/ErrorLogs folder

Like this?
content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata/document/primary%3AAndroid%2Fdata%2Fcom.zane.stardewvalley%2Ffiles%2FErrorLogs%2FSMAPI-latest.txt

**Comment by TeamDeity** [comment]
Or no?

**Comment by Zencee** [comment]
move the log txt file to a more accessible folder like downloads. Then parse it on https://smapi.io/log. Afterwards send the link back here

**Comment by TeamDeity** [comment]
> move the log txt file to a more accessible folder like downloads. Then parse it on https://smapi.io/log. Afterwards send the link back here

Okay here you go.
https://smapi.io/log/1e6a50143c684309a7a61318b61c21ac

**Comment by Zencee** [comment]
there were too many invalid values in your Mods, you probably messed up some of their config files or something, better check out each mods config file and look up the correct values to be placed usually they can be found inside the content.json file.

**Comment by TeamDeity** [comment]
> there were too many invalid values in your Mods, you probably messed up some of their config files or something, better check out each mods config file and look up the correct values to be placed usually they can be found inside the content.json file.

I didn't touch any of the config files. They were like that when I downloaded them and it was like that. Then I changed them and they still are like that. I can try and see what each contents original file is.

**Comment by Zencee** [comment]
> > there were too many invalid values in your Mods, you probably messed up some of their config files or something, better check out each mods config file and look up the correct values to be placed usually they can be found inside the content.json file.
> 
> I didn't touch any of the config files. They were like that when I downloaded them and it was like that. Then I changed them and they still are like that. I can try and see what each contents original file is.

I see then you can check out your parsed log that you sent, the orange texts specifically. It should give you a clue unto which mods has invalid values on them which could definitely crash your game.

**Comment by TeamDeity** [comment]
> > > there were too many invalid values in your Mods, you probably messed up some of their config files or something, better check out each mods config file and look up the correct values to be placed usually they can be found inside the content.json file.
> > 
> > 
> > I didn't touch any of the config files. They were like that when I downloaded them and it was like that. Then I changed them and they still are like that. I can try and see what each contents original file is.
> 
> I see then you can check out your parsed log that you sent, the orange texts specifically. It should give you a clue unto which mods has invalid values on them which could definitely crash your game since they are alot.

Hello. I ended up finding out that those mods were not causing Smapi to have an infinite loading screen. One of the other mods that didn't have any warnings may be the cause as the issue of infinite loading is still happening even after I had put majority of my mods outside somewhere else(so I don't have to delete them). So I'm trying to figure out which one or ones are the cause.

**Comment by Zencee** [comment]
> > > > there were too many invalid values in your Mods, you probably messed up some of their config files or something, better check out each mods config file and look up the correct values to be placed usually they can be found inside the content.json file.
> > > 
> > > 
> > > I didn't touch any of the config files. They were like that when I downloaded them and it was like that. Then I changed them and they still are like that. I can try and see what each contents original file is.
> > 
> > 
> > I see then you can check out your parsed log that you sent, the orange texts specifically. It should give you a clue unto which mods has invalid values on them which could definitely crash your game since they are alot.
> 
> Hello. I ended up finding out that those mods were not causing Smapi to have an infinite loading screen. One of the other mods that didn't have any warnings may be the cause as the issue of infinite loading is still happening even after I had put majority of my mods outside somewhere else(so I don't have to delete them). So I'm trying to figure out which one or ones are the cause.

Ok try removing your pytk that mod isn't really necessary anymore.

**Comment by TeamDeity** [comment]
> > > > > there were too many invalid values in your Mods, you probably messed up some of their config files or something, better check out each mods config file and look up the correct values to be placed usually they can be found inside the content.json file.
> > > > 
> > > > 
> > > > I didn't touch any of the config files. They were like that when I downloaded them and it was like that. Then I changed them and they still are like that. I can try and see what each contents original file is.
> > > 
> > > 
> > > I see then you can check out your parsed log that you sent, the orange texts specifically. It should give you a clue unto which mods has invalid values on them which could definitely crash your game since they are alot.
> > 
> > 
> > Hello. I ended up finding out that those mods were not causing Smapi to have an infinite loading screen. One of the other mods that didn't have any warnings may be the cause as the issue of infinite loading is still happening even after I had put majority of my mods outside somewhere else(so I don't have to delete them). So I'm trying to figure out which one or ones are the cause.
> 
> Ok try removing your pytk that mod isn't really necessary anymore.

I already did and that wasn't the problem. I have every reason to believe it's Space Core but most of my mods take Space Core. Json Assets could also be the issue. I already tested out Smapi Stardew without any mods and it worked but with mods? Nope. So it's a specific mod but I don't know what. I might just have to go in and put one mod in at a time and load the game up to see if that will help me find the issue.

**Comment by kwiknik78** [comment]
Try checking your versions against a known working list such as this one:
https://android.stardew.rocks

**Comment by TeamDeity** [comment]
> Try checking your versions against a known working list such as this one: https://android.stardew.rocks

I no longer am in need of help. Spacecore and Json Assets just aren't working for me. Everything else is working without any issues so far.
