### ISSUE TITLE
SMAPI ALWAYS CRASHING

### ISSUE THREAD

**Issue by MaiaCalusim** [ZaneYork/SMAPI-Android-Installer#61]
Playing Stardew valley. And tried installing v1.6.6 and it keeps on crashing.
![

**Comment by MaiaCalusim** [comment]
HEEEEELLLPPPPP

**Comment by lividhen** [comment]
what version is stardew valley? (go to app info then... storage, i think) It is not compatible with 1.4.5.148. If it is, downgrade to 1.5.4.145. If you have mods already installed, try removing them.

**Comment by MaiaCalusim** [comment]
My version is 1.4.5.148. how can I doengrade it to 1.5.4.145?

**Comment by BunnyX53** [comment]
> My version is 1.4.5.148. how can I doengrade it to 1.5.4.145?

I want to know this too. I havent been able to

**Comment by lividhen** [comment]
> 
> 
> My version is 1.4.5.148. how can I doengrade it to 1.5.4.145?

Well, there is no official way too... my recommendation is: Take to google with terms like "stardew valley 1.5.4.145" and "apk" 🙄

**Comment by BunnyX53** [comment]
Tried that. Didn't work

**Comment by lividhen** [comment]
> 
> 
> Tried that. Didn't work

unless you used smali to turn off signature verification you need to uninstall it the re-install the older one and disable automatic updates in google play.

**Comment by vidhitchauhann** [comment]
Just google the version you wanna download and download the apk and the obb file then install the apk and place the obb file in android/obb/  that's it

**Comment by vidhitchauhann** [comment]
download it from here : https://rexdlfile.com/index.php?id=stardew-valley-apk

( pls delete the link if it's not allowed, I'm not sure tho) :3

**Comment by BunnyX53** [comment]
> Just google the version you wanna download and download the apk and the obb file then install the apk and place the obb file in android/obb/ that's it


> > Tried that. Didn't work
> 
> unless you used smali to turn off signature verification you need to uninstall it the install the older one and disable automatic updates in google play. Idk how the mobile version handles save data, so you may need to find a way to back it up first.

That must be the problem. Dont think I dare delete it just in case 😬

**Comment by vidhitchauhann** [comment]
downloading the apk and obb works fine for me no sich issue
