### ISSUE TITLE
forge and dialogue choices.

### ISSUE THREAD

**Issue by PracticeCurious** [ZaneYork/SMAPI-Android-Installer#653]
i made a reddit post about it on smapi: https://www.reddit.com/r/SMAPI/comments/1963fs3/android_player_anyone_else_having_this_trouble/

but here is the issues:

![g49zgf252bcc1](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/155328878/be91ee6d-ba59-49a3-9801-2bf362fc5496)

![4uql2hks1bcc1](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/155328878/e4d66b0d-4d19-44aa-ab74-88b35e0732cb)

forge duplicate items/tools/weapon and it's broken

the dialogue is huge that it doesn't fit the screen when choosing choices in heart events

**Comment by Zencee** [comment]
the huge dialog box is an old problem.. can't fix it for now unless zane fixes it.

the forge bug is due to spacecore. Removing spacecore mid game won't fix your save file, so starting a new game without spacecore is probably the only way to fix it.

**Comment by PracticeCurious** [comment]
> the huge dialog box is an old problem.. can't fix it for now unless zane fixes it.
> 
> the forge bug is due to spacecore. Removing spacecore mid game won't fix your save file, so starting a new game without spacecore is probably the only way to fix it.

i need space core for SVE so removing that would break the game

**Comment by PracticeCurious** [comment]
> the huge dialog box is an old problem.. can't fix it for now unless zane fixes it.
> 
> the forge bug is due to spacecore. Removing spacecore mid game won't fix your save file, so starting a new game without spacecore is probably the only way to fix it.

ok, after removing "Space core" and doing all the enchantments i need to do, it works fine now.
now i won't need the forge.

i just have to re-install space core of courese

**Comment by Zencee** [comment]
> > the huge dialog box is an old problem.. can't fix it for now unless zane fixes it.
> > the forge bug is due to spacecore. Removing spacecore mid game won't fix your save file, so starting a new game without spacecore is probably the only way to fix it.
> 
> ok, after removing "Space core" and doing all the enchantments i need to do, it works fine now. now i won't need the forge.
> 
> i just have to re-install space core of courese

cool glad it worked out for you
