### ISSUE TITLE
How do i fix this 

### ISSUE THREAD

**Issue by Cantthinkofan** [ZaneYork/SMAPI-Android-Installer#656]
Error on verbose something something
![Screenshot_20240123_065337](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/152628958/0eda80d2-6be5-48b3-9b72-225f5ee8ee78)
![Screenshot_20240123_065332](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/152628958/b68a3a10-cb36-49f8-8921-9e7870213136)
![Screenshot_20240123_065321](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/152628958/7fd37065-3368-4bf1-bc11-8010867f0018)
![Screenshot_20240123_065326](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/152628958/49001987-0439-4b30-a5bf-6298ed233391)
![Screenshot_20240123_064410](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/152628958/9c50278d-4c27-47ea-b842-7e63225c133f)
![Screenshot_20240123_055235](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/152628958/7a39765b-8bfe-4d79-b848-2d1334c80cf2)

**Comment by Zencee** [comment]
this happens when some of your smapi-internal files inside `com.zane` are corrupted. This could solve your problem #503

**Comment by Cantthinkofan** [comment]
Thank you it got solve
