### ISSUE TITLE
"Found 1 mod with warnings" and mods not running.

### ISSUE THREAD

**Issue by wiredlandline** [ZaneYork/SMAPI-Android-Installer#663]
so, I've somehow fixed whatever dependency issue smapi was running into when booting up but now it doesn't run any mod I install. It shows them in the installer, they're 100% active but when it boots up the terminal simply shows the keyboard and console mods along with the message that they've found one mod with warnings. I've installed and installed the mods. I've checked if they're compatible with android and smapi. I've done absolutely everything I could think of doing but they just refuse to run. Before someone mentions it, I'm not on the latest sdv version but .39

**Comment by Zencee** [comment]
you must've placed the mods on the wrong folder, place them inside `android/data/com.zane.stardewvalley/files/mods`

**Comment by wiredlandline** [comment]
> you must've placed the mods on the wrong folder, place them inside `android/data/com.zane.stardewvalley/files/mods`

i most definitely haven't, i wish that was the issue but i've checked after every single time and it they were in the right place.

**Comment by Zencee** [comment]
can you perhaps send your log file?

**Comment by wiredlandline** [comment]
> can you perhaps send your log file?

quick question, will the log file be deleted or changed if you delete the app? because i thought it was perhaps an issue with missing dependencies and deleted then installed it multiple times.

**Comment by Zencee** [comment]
> > can you perhaps send your log file?
> 
> quick question, will the log file be deleted or changed if you delete the app? because i thought it was perhaps an issue with missing dependencies and deleted then installed it multiple times.

your log gets refreshed everytime you run the app.

**Comment by wiredlandline** [comment]
> > > can you perhaps send your log file?
> > 
> > 
> > quick question, will the log file be deleted or changed if you delete the app? because i thought it was perhaps an issue with missing dependencies and deleted then installed it multiple times.
> 
> your log gets refreshed everytime you run the app.

Alright so im guessing I'll have to replicate the issue then send a log.

**Comment by Zencee** [comment]
> > > > can you perhaps send your log file?
> > > 
> > > 
> > > quick question, will the log file be deleted or changed if you delete the app? because i thought it was perhaps an issue with missing dependencies and deleted then installed it multiple times.
> > 
> > 
> > your log gets refreshed everytime you run the app.
> 
> Alright so im guessing I'll have to replicate the issue then send a log.

yeah you can send it or just check it out yourself

**Comment by wiredlandline** [comment]
> > > > > can you perhaps send your log file?
> > > > 
> > > > 
> > > > quick question, will the log file be deleted or changed if you delete the app? because i thought it was perhaps an issue with missing dependencies and deleted then installed it multiple times.
> > > 
> > > 
> > > your log gets refreshed everytime you run the app.
> > 
> > 
> > Alright so im guessing I'll have to replicate the issue then send a log.
> 
> yeah you can send it or just check it out yourself

alright, how do i get a log again? i've clicked on the log button and that has done absolutely nothing.

**Comment by wiredlandline** [comment]
> > > > > > > can you perhaps send your log file?
> > > > > > 
> > > > > > 
> > > > > > quick question, will the log file be deleted or changed if you delete the app? because i thought it was perhaps an issue with missing dependencies and deleted then installed it multiple times.
> > > > > 
> > > > > 
> > > > > your log gets refreshed everytime you run the app.
> > > > 
> > > > 
> > > > Alright so im guessing I'll have to replicate the issue then send a log.
> > > 
> > > 
> > > yeah you can send it or just check it out yourself
> > 
> > 
> > alright, how do i get a log again? i've clicked on the log button and that has done absolutely nothing.
> 
> your log should be inside your `com.zane/files/error` transfer the txt file to an accessible folder like downloads and upload it in https://smapi.io/log under the android tab

okay so one small problem; my phone does not organize that way so i do not have zane file. i had to figure it out when i had another issue with missing dependencies that what people see as com.zane is just the stardew valley file. i also do not have a error one.

**Comment by Zencee** [comment]
> > > > > > > > can you perhaps send your log file?
> > > > > > > 
> > > > > > > 
> > > > > > > quick question, will the log file be deleted or changed if you delete the app? because i thought it was perhaps an issue with missing dependencies and deleted then installed it multiple times.
> > > > > > 
> > > > > > 
> > > > > > your log gets refreshed everytime you run the app.
> > > > > 
> > > > > 
> > > > > Alright so im guessing I'll have to replicate the issue then send a log.
> > > > 
> > > > 
> > > > yeah you can send it or just check it out yourself
> > > 
> > > 
> > > alright, how do i get a log again? i've clicked on the log button and that has done absolutely nothing.
> > 
> > 
> > your log should be inside your `com.zane/files/error` transfer the txt file to an accessible folder like downloads and upload it in https://smapi.io/log under the android tab
> 
> okay so one small problem; my phone does not organize that way so i do not have zane file. i had to figure it out when i had another issue with missing dependencies that what people see as com.zane is just the stardew valley file. i also do not have a error one.

so you don't have a `com.zane.stardewvalley` file?

**Comment by wiredlandline** [comment]
no I DO have a stardew valley file, it just isn't named com.zane or include it. but it has the content, smapi and mod folders.

**Comment by Zencee** [comment]
> no I DO have a stardew valley file, it just isn't named com.zane or include it. but it has the content, smapi and mod folders.

I see. You are confusing the `Stardew Valley` folder to be the same as the `com.zane` folder. Those two folders are different, the `Stardew Valley` folder is only needed for the initial start up of the game where it asks you to locate that folder once opening the game for the first time. After locating it, the game asks you to restart once it successfully migrated automatically the files inside the `Stardew Valley` folder to a new folder which is the `com.zane.stardewvalley`.

**Comment by wiredlandline** [comment]
> > no I DO have a stardew valley file, it just isn't named com.zane or include it. but it has the content, smapi and mod folders.
> 
> I see. You are confusing the `Stardew Valley` folder to be the same as the `com.zane` folder. Those two folders are different, the `Stardew Valley` folder is only needed for the initial start up of the game where it asks you to locate that folder once opening the game for the first time. After locating it, the game asks you to restart once it successfully migrated automatically the files inside the `Stardew Valley` folder to a new folder which is the `com.zane.stardewvalley`.

Huh, strange. I only ever had the Stardew Valley folder with all the other stuff (content, mods, smapi). Never once did it make a folder named com.zane so I have no idea what to make of that. Thing is, the installer recognized the mods when I put them in the mod folder. They showed up on the tab, they just didn't run.

**Comment by Zencee** [comment]
> Huh, strange. I only ever had the Stardew Valley folder with all the other stuff (content, mods, smapi). Never once did it make a folder named com.zane so I have no idea what to make of that. Thing is, the installer recognized the mods when I put them in the mod folder. They showed up on the tab, they just didn't run.

the installer doesn't work the same way as before like 1.4.5. Infact the installer is quite useless right now since it can't access our android/data files due to androids new strict policy. 

my suggestion is to manually create the com.zane folder to bypass all errors you may encounter from the installer. Download this file and unzip it, paste it inside your Android/data folder and open your game it should fix it. https://www.mediafire.com/file/9odnwrnrazk8uee/com.zane.stardewvalley.zip/file

**Comment by wiredlandline** [comment]
> > Huh, strange. I only ever had the Stardew Valley folder with all the other stuff (content, mods, smapi). Never once did it make a folder named com.zane so I have no idea what to make of that. Thing is, the installer recognized the mods when I put them in the mod folder. They showed up on the tab, they just didn't run.
> 
> the installer doesn't work the same way as before like 1.4.5. Infact the installer is quite useless right now since it can't access our android/data files due to androids new strict policy.
> 
> my suggestion is to manually create the com.zane folder to bypass all errors you may encounter from the installer. Download this file and unzip it, paste it inside your Android/data folder and open your game it should fix it. https://www.mediafire.com/file/9odnwrnrazk8uee/com.zane.stardewvalley.zip/file

Hey, so it makes a bunch of other folders along with the com.zane.stardewvalley folder once i extract it, is that normal? Also, should I delete the other smapi internal file so it doesn't run upon having two of the same?

**Comment by wiredlandline** [comment]
So I messed around with it, deleted all those empty folders (given they were duplicates of folders already found in `com.zane.stardewvalley` and deleted the smapi folder in `StardewValley` along with the mod one. It runs fine, it's booting up but the mod I installed (CJB) is once again *not* running or showing up. (Not in the installer program, I'm not looking at that anymore but it doesn't even show up in the console once I boot up)

https://smapi.io/log/7693e1d8be8e45c9887af07feea1cd96 here's my log, for some reason the mod also does not show up there. (double checked, it is where it should be and mod compatibility says it's compatible)

**Comment by Zencee** [comment]
> So I messed around with it, deleted all those empty folders (given they were duplicates of folders already found in `com.zane.stardewvalley` and deleted the smapi folder in `StardewValley` along with the mod one. It runs fine, it's booting up but the mod I installed (CJB) is once again _not_ running or showing up. (Not in the installer program, I'm not looking at that anymore but it doesn't even show up in the console once I boot up)
> 
> https://smapi.io/log/7693e1d8be8e45c9887af07feea1cd96 here's my log, for some reason the mod also does not show up there. (double checked, it is where it should be and mod compatibility says it's compatible)

you must've placed the cjb mod on the wrong folder again
![received_3874438636112256](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/129819788/11a6f00c-097e-4061-826f-3cfecd0e2da7)
Go to Android folder > data > com.zane.stardewvalley > files > Mods (place it here)

**Comment by wiredlandline** [comment]
> > > > Huh, strange. I only ever had the Stardew Valley folder with all the other stuff (content, mods, smapi). Never once did it make a folder named com.zane so I have no idea what to make of that. Thing is, the installer recognized the mods when I put them in the mod folder. They showed up on the tab, they just didn't run.
> > > 
> > > 
> > > the installer doesn't work the same way as before like 1.4.5. Infact the installer is quite useless right now since it can't access our android/data files due to androids new strict policy.
> > > my suggestion is to manually create the com.zane folder to bypass all errors you may encounter from the installer. Download this file and unzip it, paste it inside your Android/data folder and open your game it should fix it. https://www.mediafire.com/file/9odnwrnrazk8uee/com.zane.stardewvalley.zip/file
> > 
> > 
> > Hey, so it makes a bunch of other folders along with the com.zane.stardewvalley folder once i extract it, is that normal? Also, should I delete the other smapi internal file so it doesn't run upon having two of the same?
> > ![Screenshot_20240213-232247_My Files](https://private-user-images.githubusercontent.com/159625381/304620789-7e7c3690-db19-424c-9394-1705120f874d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDI4NTUsIm5iZiI6MTcwNzkwMjU1NSwicGF0aCI6Ii8xNTk2MjUzODEvMzA0NjIwNzg5LTdlN2MzNjkwLWRiMTktNDI0Yy05Mzk0LTE3MDUxMjBmODc0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwOTIyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTJmNzNkMjEwMGUyOWZlN2ZhMTQ1N2EyZThhNTU5NTYyZmE4MjE4ZTc3ODM5YzY2MDVlMjU2MWFlYzkwYmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HlXcujtcIHbj2rmvsSJXDBowLrvQHRrbcu-3UtiBizg) it looks something like this and it's really confusing me.
> 
> idk how you manage to get those files.. you only need the com.zane.stardewvalley plus yours is in the wrong directory it should not be inside the internal storage but on android/data folder. So you can safely delete all these files in this picture to avoid confusion

Oh shit uh. My phone DOES NOT have `android/data`, most likely because it's a samsung.

**Comment by wiredlandline** [comment]
> > > > Huh, strange. I only ever had the Stardew Valley folder with all the other stuff (content, mods, smapi). Never once did it make a folder named com.zane so I have no idea what to make of that. Thing is, the installer recognized the mods when I put them in the mod folder. They showed up on the tab, they just didn't run.
> > > 
> > > 
> > > the installer doesn't work the same way as before like 1.4.5. Infact the installer is quite useless right now since it can't access our android/data files due to androids new strict policy.
> > > my suggestion is to manually create the com.zane folder to bypass all errors you may encounter from the installer. Download this file and unzip it, paste it inside your Android/data folder and open your game it should fix it. https://www.mediafire.com/file/9odnwrnrazk8uee/com.zane.stardewvalley.zip/file
> > 
> > 
> > Hey, so it makes a bunch of other folders along with the com.zane.stardewvalley folder once i extract it, is that normal? Also, should I delete the other smapi internal file so it doesn't run upon having two of the same?
> > ![Screenshot_20240213-232247_My Files](https://private-user-images.githubusercontent.com/159625381/304620789-7e7c3690-db19-424c-9394-1705120f874d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDI4NTUsIm5iZiI6MTcwNzkwMjU1NSwicGF0aCI6Ii8xNTk2MjUzODEvMzA0NjIwNzg5LTdlN2MzNjkwLWRiMTktNDI0Yy05Mzk0LTE3MDUxMjBmODc0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwOTIyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTJmNzNkMjEwMGUyOWZlN2ZhMTQ1N2EyZThhNTU5NTYyZmE4MjE4ZTc3ODM5YzY2MDVlMjU2MWFlYzkwYmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HlXcujtcIHbj2rmvsSJXDBowLrvQHRrbcu-3UtiBizg) it looks something like this and it's really confusing me.
> 
> idk how you manage to get those files.. you only need the com.zane.stardewvalley plus yours is in the wrong directory it should not be inside the internal storage but on android/data folder. So you can safely delete all these files in this picture to avoid confusion

Well fuck, I can't put anything there. 
![Screenshot_20240214-194348_My Files](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/159625381/62d335e5-ce5e-469d-89a3-b27f910be852)
(I've tried, it doesn't give me the option to paste or to move anything inside of there)

**Comment by Zencee** [comment]
> (I've tried, it doesn't give me the option to paste or to move anything inside of there)

yeah some phones have heavy restrictions on their data folders. Try using 3rd party apps first like Zarchiver or MTmanager it might work, if not then only connecting to a computer would.

**Comment by wiredlandline** [comment]
I got it to show me the files using RS file explorer and now it is working as intended, thank you so much for the continued help and I am so sorry if my clear lack of android knowledge made helping me a tad frustrating. Again, thank you.
