### ISSUE TITLE
Community center not working?

### ISSUE THREAD

**Issue by Yash2772632** [ZaneYork/SMAPI-Android-Installer#664]
After the cutscene where mayor Lewis introduces the community center, I tried to enter but it would just stay on a black screen
Here is my log, maybe you guys can help me on which mod is doing it
https://smapi.io/log/e422efc2176347a2af3230c6a39e4b3e

**Comment by Zencee** [comment]
> After the cutscene where mayor Lewis introduces the community center, I tried to enter but it would just stay on a black screen Here is my log, maybe you guys can help me on which mod is doing it 

do you get black screen all the time you enter? your log says its due to loading one of ridgeside valleys event, your game looped trying to open that event until it crashed.

**Comment by Yash2772632** [comment]
Yeah

**Comment by Zencee** [comment]
> Yeah

try removing your event repeater mod for now and see if it still gives you blackscreen.

**Comment by Yash2772632** [comment]
Tried it still didn't work

**Comment by Yash2772632** [comment]
Did you see the red text while scrolling down it said something about 37

**Comment by Zencee** [comment]
> Did you see the red text while scrolling down it said something about 37

Check again your log and click trace button you will see everytime a ridgeside event is being loaded your game creates loop errors, idk if its a ridgeside bug or conflicting mods.
![Screenshot_20240211-192129_1](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/129819788/4868d129-8a54-4122-bad7-4cf8c5a5648a)

**Comment by Haerinah** [comment]
maybe try looking at your rsv config files for clues you might have entered an invalid key

**Comment by Yash2772632** [comment]
Do you know where in the config files do I look

**Comment by Yash2772632** [comment]
Never mind I got it fixed I just reinstalled RSV and created a new world
