### ISSUE TITLE
There is no com.zane file in my android data?

### ISSUE THREAD

**Issue by Deweee19** [ZaneYork/SMAPI-Android-Installer#665]
Like the tittle said, i already try a lot of things like downloading the com.zane file and place it on my android data and still didnt work, because everytime i moded the stardew with smapi, there is no com.zane file appear, the only file that appear are the "StardewValley" file that not placed in android data
![IMG_20240211_232609](https://github.com/ZaneYork/SMAPI-Android-Installer/assets/159713482/7ba25dbf-3373-4e92-9855-d491266338a5)
So im really confuse of trying to find the com.zane data to put my mod and to make the game work with no error warning at the beginning, im using the 1.4.5 version, because when im using the 1.5(newest) version of the game, it always force closed when i moded it, because a lot of people saying that the smapi not compatible enough for the newest version, is there any fix for the error i get and the missing com.zane file that im try to make it appear?

**Comment by Zencee** [comment]
this may help you https://github.com/ZaneYork/SMAPI-Android-Installer/issues/658#issuecomment-1918455182

**Comment by Deweee19** [comment]
> this may help you [#658 (comment)](https://github.com/ZaneYork/SMAPI-Android-Installer/issues/658#issuecomment-1918455182)

Man u are truly a savior!, thanks for the help, i really frustated to try solve this problem
