### ISSUE TITLE
Android 10 with game version 1.4.5.148

### ISSUE THREAD

**Issue by hfmiguel** [ZaneYork/SMAPI-Android-Installer#67]
Hi  , 

Any prevision to compatibility with android 10 and latest game version ?

I came here every day with hope to get new update to play =(

**Comment by lividhen** [comment]
so far there is no update for 1.4.5.148 but 1.4.5.145 works on android 10

**Comment by hfmiguel** [comment]
> so far there is no update for 1.4.5.148 but 1.4.5.145 works on android 10

I'm try with version 145 but when i open the game , this close and i dont get nothing  on smapi logs

**Comment by lividhen** [comment]
> 
> 
> > so far there is no update for 1.4.5.148 but 1.4.5.145 works on android 10
> 
> I'm try with version 145 but when i open the game , this close and i dont get nothing on smapi logs

you could also try 147. I'm having no issues with 145, so thats odd... What is your vendor? (samsung, oneplus, etc)

**Comment by hfmiguel** [comment]
> > > so far there is no update for 1.4.5.148 but 1.4.5.145 works on android 10
> > 
> > 
> > I'm try with version 145 but when i open the game , this close and i dont get nothing on smapi logs
> 
> you could also try 147. I'm having no issues with 145, so thats odd... What is your vendor? (samsung, oneplus, etc)

I have a galaxy a71 . I'm play the version 145 ( cracked ) . But i buy the play store version to get  more easy the updates and try some mods that not work fine on versikn 147 . But i cant play the version 148 with smapi 1.7 and 1.6.6

**Comment by LuxiMalikSuzumori** [comment]
Smapi for android has been broken for a while. Both developers are away/busy. No known solution except to use an APK version thats 147 or lower.

**Comment by ZaneYork** [comment]
Updated
