### ISSUE TITLE
SMAPI keep crashing each time I want to launch it

### ISSUE THREAD

**Issue by ReginaVW** [ZaneYork/SMAPI-Android-Installer#673]
Basically I want to play SMAPI but in mobile but I can't, because it kept crashing each time I want to launch it, it already does have this issue for me since the last 5 SMAPI versions, even in 3.18.3.3 it also does the same thing! Does anyone has a fix or something else?

**Comment by Zencee** [comment]
delete your smapi stardew app and replace it with this one https://www.mediafire.com/file/7en2uhbj0p6jfeg/Smapi_SDV.apk/file

**Comment by ReginaVW** [comment]
Actually, my iPhone works absolutely fine with the old non-SDV SMAPI but let's pretend that iPhones doesn't exist.

**Comment by ReginaVW** [comment]
Thank you Zencee
