### ISSUE TITLE
Game won't load

### ISSUE THREAD

**Issue by steamboi96** [ZaneYork/SMAPI-Android-Installer#68]
everything seems to perfect in the logs and not even using any heavy visual mods. but after clicking on my save file it won't load and the music keep Playing and suddenly get crashed after 2-3min. I thought maybe my save was corrupted, but the same thing happened with the new save file. I'm on android 10 custom rom. pls help
https://smapi.io/log/7acd066d1c3d4bbc97e19122eef7f287

**Comment by wally232** [comment]
Custom Furniture mode is not available on mobile. Try deleting it.
