### ISSUE TITLE
Smapi Android Still Crashing PLEASE FIX

### ISSUE THREAD

**Issue by LuxiMalikSuzumori** [ZaneYork/SMAPI-Android-Installer#70]
With the 1.5 Update just released, I would like to be able to play mods without it crashing seconds after launching. I can't even load it. Its been 2 months since SMAPI was updated for android and it's STILL broken. I really hope this will be fixed soon please.

NOTE: Using ANY apk on my phone causes malware to affect my phone so apk is not an option.

**Comment by vidhitchauhann** [comment]
you do know that 1.5 on mobile won't be coming till February or even take more than that?

**Comment by LuxiMalikSuzumori** [comment]
> you do know that 1.5 on mobile won't be coming till February or even take more than that?

Even so, its still broken for 1.4

**Comment by vidhitchauhann** [comment]
he will fix it whenever he comes back online, which he hasn't been since mid of October. Plus just like you I updated it to the latest version but got my game crashed, so from that day I've been using the apk (third party) to play it.

**Comment by LuxiMalikSuzumori** [comment]
The apk file for me ends up being malicious and causes multiple pop up ads on my home screen and during other apps. so i cant use the apk

**Comment by vidhitchauhann** [comment]
it is very weird that an apk is causing it.Because it looks like you're using an app which enables ads, and for your information stardew valley contains no ads be it a third party app or from playstore. I've downloaded it from the same link that I gave you, didn't get any kind of popup while using the device

**Comment by LuxiMalikSuzumori** [comment]
third parties can add whatever they want to it. including ads. my antivirus (Norton) informed me that the file (which i downloaded from your link) was malicious and should be removed. now, unless you have important info to share for the actual program and NOT an apk, please leave
