### ISSUE TITLE
length=3332; index=3332

### ISSUE THREAD

**Issue by Stepan543** [ZaneYork/SMAPI-Android-Installer#708]
I wanted to download SMAPI, but here it is:
![Screenshot_2024-07-12-18-11-33-431_com zane smapiinstaller](https://github.com/user-attachments/assets/1e3daa8f-a588-4a7b-b780-eb794d227e48)

**Comment by Zencee** [comment]
check out #590 it's a temporary fix but it should work

**Comment by Stepan543** [comment]
Thanks
