### ISSUE TITLE
Manifest denied Access

### ISSUE THREAD

**Issue by MaraSgit** [ZaneYork/SMAPI-Android-Installer#712]
Hello, i installed some mods but when they are in `StardewValley/Mods` they don't load at all and when they are in the android data mod folder they throw this err and don't load. Are there any fixes?

![Screenshot_20240723_112730.jpg](https://github.com/user-attachments/assets/de49c81a-701a-402e-a753-6d476339c748)

**Comment by Zencee** [comment]
watch mikochan's vid about ridgeside village for android on youtube. Also yeah mods should always be placed inside `com.zane.stardewvalley` folder

**Comment by MaraSgit** [comment]
> watch mikochan's vid about ridgeside village for android on youtube. Also yeah mods should always be placed inside `com.zane.stardewvalley` folder

Did not fix the problem, the problem is that it cannot load any mod manifest exept the two pre-installed

**Comment by Zencee** [comment]
> > watch mikochan's vid about ridgeside village for android on youtube. Also yeah mods should always be placed inside `com.zane.stardewvalley` folder
> 
> Did not fix the problem, the problem is that it cannot load any mod manifest exept the two pre-installed

have you tried reinstalling your smapi? That always fixes that manifest bug caused by bugged smapi-internal files.

**Comment by MaraSgit** [comment]
> > > watch mikochan's vid about ridgeside village for android on youtube. Also yeah mods should always be placed inside `com.zane.stardewvalley` folder
> > 
> > Did not fix the problem, the problem is that it cannot load any mod manifest exept the two pre-installed
> 
> have you tried reinstalling your smapi? That always fixes that manifest bug caused by bugged smapi-internal files.

I reinstalled it twice and then it started loading mods but i had to reinstall some and then it started working, thanks
