### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Bexeylover** [ZaneYork/SMAPI-Android-Installer#715]
The virtual keyboard for SMAPI android isn't showing the new keys I added in config. I went to reddit I even join a stardew valley discord and I was just straight up told they couldn't help me. Since I had SMAPI for android. This is just my last solution.

**Comment by Zencee** [comment]
did you place your newly edited virtual keyboard folder inside android/data `com.zane.stardewvalley` mods folder?

**Comment by Bexeylover** [comment]
I edit in the smapi. Am im suppose to edit the file I'm the stardew mods folder? I have tried that but when I did edit the file from the mod itself instead of inside of smapi. I ended up breaking the mod and had to reinstall smapi. To get the keyboard to work again

**Comment by Zencee** [comment]
> I edit in the smapi. Am im suppose to edit the file in the stardew mods folder? I have tried that but when I did edit the file from the mod itself instead of inside of smapi. I ended up breaking the mod and had to reinstall smapi. To get the keyboard to work again

its fine to edit it in the smapi graphics editor but after editing it you need to copy that file (virtual keyboard) back to `android/data/com.zane.stardewvalley` folder for it to work in your game. Since mods only work if placed inside com.zane 📁

**Comment by Bexeylover** [comment]
Oh! I wasn't doing that I was just editing it in smapi and then loading the game. I did not know I had to copy the edited file and put it in my mods folder. Tysm this help alot I finally got a new key added tysm.
