### ISSUE TITLE
Cant load SV 1.4.5.151 please update :(

### ISSUE THREAD

**Issue by namgper** [ZaneYork/SMAPI-Android-Installer#73]
I cant load smapi on SV new update, when i try to play the game, the game forceclose. Thank you

**Comment by thegoko** [comment]
It can only work up to 1.4.5.147 for now.

**Comment by namgper** [comment]
Yes i download SV 1.4.5.145 and its work 👍🏻

**Comment by ZaneYork** [comment]
Updated
