### ISSUE TITLE
Smapi stardew crashes

### ISSUE THREAD

**Issue by Rejecthumanityreturntomonke** [ZaneYork/SMAPI-Android-Installer#737]
When i open smapi it just crashes i've tried reinstalling smapi and installing 1.5.6.39 

I did open it up one time but it just it just showed a error message

**Comment by Jeckabnormalism** [comment]
What error?

**Comment by Rejecthumanityreturntomonke** [comment]
> What error?

Its a giant one, came from the sdv version i installed here, i think it would happen same if i installed the normal one i have some screenshots from the error


![Screenshot_20241031_170819.jpg](https://github.com/user-attachments/assets/995118ee-a604-47e4-a2d2-1237c19cefd6)

![Screenshot_20241031_170846.jpg](https://github.com/user-attachments/assets/6b29d9f3-0faa-4b06-aa![Screenshot_20241031_170712.jpg](https://github.com/user-attachments/assets/b60cc64b-6cf9-4d6d-bf05-de1ad19f7b1d)

g](https://github.com/user-attachments/assets/c2dd0b70-ec26-449e-903b-51e4242337c0)

![Uploading Screenshot_20241031![Screenshot_20241031_170748.jpg](https://github.com/user-attachments/assets/24b8c707-baa9-4fbd-a31f-5ffe080e7da0)

![Screenshot_20241031_170840.jpg](https://github.com/user-attachments/assets/f48371c6-9a3a-434f-8c46-daf686f2b4e4)

6bd2f-4b53-4e9f-9812-08861f2465d9)

![Uploading Screenshot_20241031_170748.jpg …]()

![Uploading Screenshot_20241031_170840.jpg …]()

**Comment by Jeckabnormalism** [comment]
Try SDV 1.5.6.52

**Comment by Rejecthumanityreturntomonke** [comment]
> Try SDV 1.5.6.52 

Didn't work also 

Crashed in less the one second, I've seen people complaining about this crashing too but their solutions didn't work out either

**Comment by Jeckabnormalism** [comment]
I've encountered that before but I forgot how I solved it with the same device.
