### ISSUE TITLE
Can I still use Content Patcher?

### ISSUE THREAD

**Issue by KenaiHam** [ZaneYork/SMAPI-Android-Installer#75]
Content Patcher doesn't work in Stardew Valley and kept saying that it needs a new version of SMAPI, then once I downloaded an older version of Content Patcher I encountered the same problem except it says that it is outdated. Is this a SMAPI problem? Or am I just too inexperienced in this. (Side note: how do I use .xnb mods?)

**Comment by smiigs** [comment]
I'm using version 1.19 of content patcher and working fine. Make sure to use mod versions dated before Dec 2020 (before 1.5)

**Comment by KenaiHam** [comment]
Weird, because I already downloaded Content Patcher 1.19 and it said that it was outdated, so once I've seen your comment I downloaded it again and it now works?! But anyways thank you.
