### ISSUE TITLE
Smapi Stardew installer 

### ISSUE THREAD

**Issue by Faceless303** [ZaneYork/SMAPI-Android-Installer#777]
When downloading the apk I followed instructions, like giving permissions etc and when clicking install is pops up with Patching smapi, however it remains on 10% and doesn't download? 

Can someone help?

**Comment by Feell-apk** [comment]
> Ao baixar o apk, segui as instruções, como dar permissões, etc., e quando clico em instalar, aparece a mensagem Patching smapi, mas ele permanece em 10% e não baixa?
> 
> Alguém pode ajudar?

The mod has not been released for 1.6, be patient and an update will come out that will change this
