### ISSUE TITLE
Failed to install smapi

### ISSUE THREAD

**Issue by AlexandroDRK** [ZaneYork/SMAPI-Android-Installer#79]
![Screenshot_2021-01-28-13-40-49](https://user-images.githubusercontent.com/78165198/106169775-7f999300-616e-11eb-888c-fd605c810006.png)

Install closes when trying to install smapi 3.7.6

**Comment by APerson1010** [comment]
App crashes ("App keeps stopping"), when trying to install also. Everytime around 42/100.

**Comment by Caco-o-sapo** [comment]
They said that is a OOM problem. And it just crashes too. And it doesn't install.

**Comment by Caco-o-sapo** [comment]
![Screenshot_20210128-140521.png](https://user-images.githubusercontent.com/57275984/106174705-17e64680-6174-11eb-87da-d9379f4cf23f.png)

**Comment by APerson1010** [comment]
If you rename the base.apk.patched to SMAPI.apk and click it, it will try to install, but ultimately fails. Even has the pufferchicken icon

**Comment by ZaneYork** [comment]
> They said that is a OOM problem. And it just crashes too. And it doesn't install.

Try latest 3.7.6.4 version, it has optimized the memory consumption ( form 380M to 310M). It may helps

**Comment by APerson1010** [comment]
Installed the 3.7.6.4 version, it waited a little while, but it successfully installed.

**Comment by ellipszist** [comment]
> > They said that is a OOM problem. And it just crashes too. And it doesn't install.
> 
> Try latest 3.7.6.4 version, it has optimized the memory consumption ( form 380M to 310M). It may helps
Successfully installed, but SMAPI Stardew Valley crashe - Android R

**Comment by ZaneYork** [comment]
Fixed in 3.7.6.5

**Comment by ellipszist** [comment]
> Fixed in 3.7.6.5

it working.

**Comment by Apolly0n** [comment]
I have the same problem even using SMAPI Android Installer v3.7.6.5
