### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [ZaneYork/SMAPI-Android-Installer#8]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by ZaneYork** [comment]
bouncycastle is not available for Android platform.
See also [spongycastle home page](https://rtyley.github.io/spongycastle/)

**Comment by Neustradamus** [comment]
@ZaneYork: Ah ah ah ah ah, thanks for your comment!
Currently Bouncy Castle last version is 1.65 and Spongy Castle last version is 1.58.
Spongy Castle is a fork of Bouncy Castle.
Please look previous links :)

Since several years, a lot of projects have already moved from Spongy Castle to Bouncy Castle because the project is dead.

You can see discussion "34" in https://github.com/rtyley/spongycastle/issues.

**Comment by ZaneYork** [comment]
Got it, will be fixed in next release

**Comment by Neustradamus** [comment]
@ZaneYork: Thanks in advance! :)

**Comment by Neustradamus** [comment]
@ZaneYork: I see always a little, can you look?
- https://github.com/ZaneYork/SMAPI-Android-Installer/search?q=spongycastle&unscoped_q=spongycastle

**Comment by ZaneYork** [comment]
Got it, I forgot to modify this comment

**Comment by Neustradamus** [comment]
@ZaneYork: Can you update Bouncy Castle to 1.69?
There were CVEs.
