### ISSUE TITLE
Smapi not installing

### ISSUE THREAD

**Issue by Caco-o-sapo** [ZaneYork/SMAPI-Android-Installer#86]
![Screenshot_20210129-095219](https://user-images.githubusercontent.com/57275984/106277382-c0011b80-6217-11eb-9fb1-854c720d21ae.png)
This is still happening with the new version. My phone is an LG K40S with the Android 10. And it's still at this point

**Comment by TheRealCube555YT** [comment]
It works perfectly for me...

**Comment by link969** [comment]
> ![Screenshot_20210129-095219](https://user-images.githubusercontent.com/57275984/106277382-c0011b80-6217-11eb-9fb1-854c720d21ae.png)
> Isso ainda está acontecendo com a nova versão. Meu telefone é um LG K40S com Android 10. E ainda está neste ponto

Para mim também

**Comment by Apolly0n** [comment]
I have the same problem

**Comment by Caco-o-sapo** [comment]
Fixed in the new version 3.5.7.6
