### ISSUE TITLE
It crashes

### ISSUE THREAD

**Issue by kingkane23** [ZaneYork/SMAPI-Android-Installer#90]
Everytime I open the SMAPI Stardew Valley it Crashes I need help

**Comment by KenaiHam** [comment]
What version are you on?

**Comment by kingkane23** [comment]
My version is 1.4

**Comment by UltimateShagiii** [comment]
1.4.?.? What are the 2 numbers?

**Comment by ZaneYork** [comment]
Duplicate of #175
