### ISSUE TITLE
Smapi remains with OOM problem.

### ISSUE THREAD

**Issue by AlexandroDRK** [ZaneYork/SMAPI-Android-Installer#92]
Even after 3 pre-updates, the smapi instaler continues to stop in the middle of the SMAPI installation process.
![Screenshot_2021-01-31-23-53-51](https://user-images.githubusercontent.com/78165198/106410417-8e5ba080-6421-11eb-9d75-1a4a3b471c5c.png)

**Comment by ZaneYork** [comment]
Try latest 3.7.6.7 version, this version needs 160MB of dalvik.vm.heapsize (OS property )
