### ISSUE TITLE
Broken Mods

### ISSUE THREAD

**Issue by Caco-o-sapo** [ZaneYork/SMAPI-Android-Installer#94]
Content Patcher, Pytk, Shoprite framework and others doesn't works. Here's the log problem. 
https://smapi.io/log/6d1967ff9f104473b0d0893f225235e7

**Comment by GeekieFreak** [comment]
Did you download the earlier versions? They probably don't work since SMAPI isn't updated to 3.9 yet.

**Comment by Caco-o-sapo** [comment]
I know, but the mods version for the smapi 3.7 aren't working

**Comment by Caco-o-sapo** [comment]
The mods in the log are for the 1.4 game

**Comment by GeekieFreak** [comment]
Yeah I tried everything I could, and it's not working for me either. But I'll keep trying and see if I can do something.

**Comment by TySunshinee** [comment]
> Yeah I tried everything I could, and it's not working for me either. But I'll keep trying and see if I can do something.

For me too! Pytk stop to work and now some mods are broken :(

**Comment by GeekieFreak** [comment]
Literally all the mods I downloaded aren't working, but hopefully everything will be fixed soon.

**Comment by Caco-o-sapo** [comment]
I updated smapi today with the newest version and still the error, here is the new log

https://smapi.io/log/6f07582dfbd645dc81f529cddc19006a

**Comment by ZaneYork** [comment]
> I updated smapi today with the newest version and still the error, here is the new log
> 
> https://smapi.io/log/6f07582dfbd645dc81f529cddc19006a

The content pack you are using is for SDV 1.5 only
